---
title: "250 - check big excel"
output: html_document
---


## Libraries
```{r}

library(dplyr)


```


## List versions of files   
```{r}

big_file_folder <- "Big_excel_table"
files <- dir(big_file_folder, pattern = "Data_xl_2020.+rds") %>% rev()
# files

data.frame(No = 1:length(files), File = files)

# ?sub

```

## Compare files  
```{r}

fileselect <- c(1,2)

dat1 <- readRDS(paste0(big_file_folder, "/", files[fileselect[1]]))
dat2 <- readRDS(paste0(big_file_folder, "/", files[fileselect[2]]))

nrow(dat1)
nrow(dat2)
nrow(dat1) - nrow(dat2)


# names(dat1)[1:22] %>% dput()
key_vars <- c("PARAM", "STATION_CODE", "LATIN_NAME", "TISSUE_NAME", "Basis")

anti12 <- anti_join(dat1, dat2, by = key_vars)
anti21 <- anti_join(dat2, dat1, by = key_vars)

nrow(anti12)
nrow(anti21)
nrow(anti12) - nrow(anti21)

anti12 %>%
  count(PARAM, STATION_CODE, LATIN_NAME, TISSUE_NAME)

anti21 %>%
  count(STATION_CODE) %>%
  arrange(desc(n))

anti12 %>%
  count(STATION_CODE) %>%
  arrange(desc(n))

anti21 %>%
  count(PARAM) %>%
  arrange(desc(n))

anti12 %>%
  count(PARAM) %>%
  arrange(desc(n))



```

