---
title: "Report for parameter (431)"
author: "DHJ"
date: "04.10.2022"
params:
  param: "HG"
  basis_medians: "WW"
  basis_trends: "WWa"
  eqsplot: "TRUE"
  ratioplot_trend: "TRUE"
output: 
  html_document:
  keep_md: false
toc: true
toc_float: true
---


```{r}

# Normal 'params' (see heading above)
# - WW for both 'basis_medians' and 'basis_trends' (exception for Hg, see special case 1 below)  
# - eqsplot "TRUE" or "FALSE" depending on whether EQS exists or not (see 431_run_markdown)   
# - ratioplot_trend "TRUE" normally (exception for SCCP and MCCP, see special case 1 below)

# Special case 1: Hg plots  
# - Needs
#   1) Combo plot for HG cod/duck with WW tiles + WWa trends
#   2) EQS/Proref plot for HG cod/duck with WW for y-axis (medians plus points) + WWa for trends (color + shape of median)
# - Set 'basis_medians' = 'WW'
# - Set 'basis_trends' = 'WWa'

# Special case 2: 'SCCP eksl. LOQ' + 'MCCP eksl. LOQ' 
# - Combo plot for both: Run from top until '04_medians_plot' - then run the part inside 'FALSE' at the end of that chunk
#     Results in combo plot without trend part  
#     (do NOT run '06_combine_plots', whcich will overwrite your plots)
# - Ratio plots: 
#     no Proref ratios for any of them
#     EQS plot for 'MCCP eksl. LOQ' - set 'ratioplot_trend' above = 'FALSE' - then run      


```


# `r params$param`  
   
```{r 01_settings, include=FALSE}

current_year <- 2021
knitr::opts_chunk$set(echo = FALSE, results = 'hold')

```

```{r 02_packages, include=FALSE}

library(dplyr)
# library(tidyr)
library(ggplot2)
library(lubridate)
library(flextable)
# library(glue)
library(readxl)
library(purrr)
library(glue)
# library(leftcensored)   # DHJ's package (https://github.com/DagHjermann/leftcensored)
library(scico)            # colour palettes incl. "Vik" (https://github.com/thomasp85/scico)

library(ggiraph)
library(cowplot)

# library(safejoin) # https://github.com/moodymudskipper/safejoin

# source("01_Get_chemical_data_NIVAbasen_functions.R")  # for get_standard_parametername()
# source("824_Report_for_scientists_functions.R")
source("420_Report_paramgroup_functions.R", encoding = "UTF-8")
source("125_Calculate_trends_leftadjusted_functions.R")
source("431_Report_parameter_functions.R")
source("002_Utility_functions.R")

```

## Medians and trends    

```{r 03_medians_data1}

#
# Get data 
#


# debugonce(get_data_medians)
dat_temporary <- list(
  get_data_medians(param = params$param, 
                   species = "Gadus morhua",
                   tissue = ifelse(params$param %in% "HG", "Muskel", "Lever"),
                   basis = params$basis_medians, 
                   include_year = current_year),
  get_data_medians(param = params$param, 
                   species = "Somateria mollissima",
                   tissue = "Blod",
                   basis = "WW", 
                   include_year = current_year),
  get_data_medians(param = params$param, 
                   species = "Somateria mollissima",
                   tissue = "Egg",
                   basis = "WW", 
                   include_year = current_year),
  get_data_medians(param = params$param, 
                   species = "Mytilus edulis",
                   tissue = "Whole soft body",
                   basis = "WW", 
                   include_year = current_year)
)


# levels(dat_temporary[[1]]$Station)
# levels(dat_temporary[[2]]$Station) 

#
# Stations - for corrrect ordering
#
lookup_stations <- read.csv("Input_data/Lookup_tables/Lookup_stationorder.csv") # %>%


```

```{r 03_medians_data2}

#
# Combine cod and eider duck as one group  
#

eider_blood <- "19N Kongsfjorden (eider duck blood)"
eider_egg <- "19N Kongsfjorden (eider duck egg)"

#
# Make 'dat_medians_list'  
#

dat_medians_list <- list()

# List element 1: cod and eider duck

if (nrow(dat_temporary[[2]]) > 0){
  dat_medians_list[[1]] <- bind_rows(
    dat_temporary[[1]],
    dat_temporary[[2]] %>% mutate(Station = eider_blood),
    dat_temporary[[3]] %>% mutate(Station = eider_egg)
  )
} else {
  dat_medians_list[[1]] <- dat_temporary[[1]]
}

dat_medians_list[[1]]$Station <- factor(dat_medians_list[[1]]$Station, 
                                        levels = c(levels(dat_temporary[[1]]$Station), eider_blood, eider_egg))

# For Hg: add an asterisk after station names for stations that are NOT length-adjusted (for Hg only)
# - these data are also used for 'ratio plots' (last year's concentrations)  
if (params$param %in% "HG" & params$basis_medians %in% "WWa"){
  # View(dat_medians_list[[1]])
  tab <- xtabs(~Basis + Station, dat_medians_list[[1]])
  not_length_adjusted <- colnames(tab)[tab[2,] == 0]
  sel <- levels(dat_medians_list[[1]]$Station) %in% not_length_adjusted
  levels(dat_medians_list[[1]]$Station)[sel] <- paste(levels(dat_medians_list[[1]]$Station)[sel], "*")
}


# levels(dat_medians_list[[1]]$Station)

# List element 2 = blue mussel

dat_medians_list[[2]] <- dat_temporary[[4]]

```


```{r 04_medians_plot, fig.width=10, fig.height=8, warning=FALSE}

proref_cols <- c(RColorBrewer::brewer.pal(6, "Blues")[5:2],
                 RColorBrewer::brewer.pal(6, "YlOrRd")[1:5])

col_func <- function(x){cols[x]}

startyr <- 2012

# Trick to avoid red frames also in legend:
# - put 'fill = Proref_ratio_cut' in aes of the first geom_tile (not in the aes of ggplot)
# - set 'alpha = 0' so there is no fill in the EQS tiles 

gg_tile_list <- list()

speciesgroup_txt <- c("cod and eider duck", "blue mussel")
speciesgroup_txt_proref <- c("cod", "blue mussel")

for (speciesgroup in 1:2){
  
  if (nrow(dat_medians_list[[speciesgroup]]) > 0){
    
    dat_medians <- dat_medians_list[[speciesgroup]] %>%
      mutate(
        Value_txt = case_when(
          is.na(FLAG1) ~ signif2(Value, 2, maxdigits = 5),
          !is.na(FLAG1) & Value > 0 ~ paste0("<", signif2(Value, 2, maxdigits = 4)),
          !is.na(FLAG1) & Value == 0 ~ "0"                                # for 'SCCP eksl. LOQ' + 'MCCP eksl. LOQ'
        )
      )
    
    # Set plot title (mercury in cod+birds is treated as a special case)
    if (params$param %in% "HG" & speciesgroup == 1 & params$basis_medians == "WW"){
      plot_title <- paste0(dat_medians$Parameter.Name[1], " (not length-adjusted) in ", speciesgroup_txt[[speciesgroup]])
    } else if (params$param %in% "HG" & speciesgroup == 1 & params$basis_medians == "WWa"){
      plot_title <- paste0(dat_medians$Parameter.Name[1], " (length-adjusted) in ", speciesgroup_txt[[speciesgroup]])
    } else {
      plot_title <- paste0(dat_medians$Parameter.Name[1], " in ", speciesgroup_txt[[speciesgroup]])
    }
    
    gg_tile_list[[speciesgroup]] <- ggplot(dat_medians, aes(MYEAR, Station)) +
      geom_tile(aes(fill = Proref_ratio_cut)) + 
      geom_tile(data = subset(dat_medians, Above_EQS %in% "Over"),
                color = "red", size = 1, height = 0.9, width = 0.9, alpha = 0) +
      geom_text(aes(label = Value_txt), nudge_y = 0, size = 3) +
      # geom_text(aes(label = LOQ_label), size = 3, nudge_y = 0.3) +
      scale_fill_manual("Proref ratio", values = proref_cols, na.value = "grey85") +
      scale_color_manual(values = c("red", "white")) +
      scale_alpha_manual(values = c(1, 0)) +
      scale_x_continuous(breaks = seq(startyr, 2020, 2), 
                         limits = c(startyr-0.5, current_year+0.5)) +
      theme_bw() +
      guides(colour = "none") +
      labs(
        title = plot_title,
        x = "Year", y = "")
    
  } else {
    
    gg_tile_list[[speciesgroup]] <- NULL
    
  }
  
}

if (FALSE){
  gg_tile_list[[1]]
  gg_tile_list[[2]]
  
  # Special case: SCCP and MCCP (eksl. LOQ)
  width_tileplot_only <- 2.7 / (2.7 + 0.75 + 1.25)
  for (speciesgroup in 1:2){
    filename <- glue::glue("Figures/431/{params$param}_combo_{speciesgroup}.png")
    ggsave(filename, gg_tile_list[[speciesgroup]], width = 14*width_tileplot_only, height = 8, dpi = 200)
  }
  
}



```

```{r 05_trends_settings}

shape_order <- c("Increasing", "Decreasing", "No change")
colour_order <- shape_order
  
trend_shapes <- c(24, 25, 21) %>% setNames(shape_order)
trend_colours <- c("red3", "green4", "grey20") %>% setNames(colour_order)
trend_fill <- c("red2", "green2", "grey20") %>% setNames(colour_order)

```

```{r 05_trends_data}

dat_trends_plot_list <- purrr::map(
  dat_medians_list, 
  get_data_trends, basis = params$basis_trends, include_year = current_year
)

# debugonce(get_data_trends)
# chck <- get_data_trends(dat_medians_list[[1]],  basis = "WWa", include_year = current_year)
# chck <- get_data_trends(dat_medians_list[[2]],  include_year = current_year)

# table(addNA(dat_trends_plot_list[[1]]$Station))
# levels(dat_trends_plot_list[[1]]$Station)
# View(dat_trends_plot_list[[1]])

```

```{r 05_trends_create_plots}

# Which species groups do we have? 
if (is.null(dat_trends_plot_list[[1]])){
  speciesgroups <- 2 
} else if (is.null(dat_trends_plot_list[[2]])){
  speciesgroups <- 1 
} else {
  speciesgroups <- 1:2
}

#
# Two things happens here: 
# 1) Store y range in a list (used to set limits), and 
# 2) add label coordinate (label_coor) to the data 
# - needed because the label coordinate is inside aes()  
# - when we didn't do this, the label of plot no. 1 was ok after making plot.no. 1, but
#   moved as we made plots no. 2,3,4.... :-o
#

y_ran <- list(list(), list())

for (speciesgroup in speciesgroups){

  dat_trends_plot_list[[speciesgroup]]$label_coor <- NA

  for (type in c("long", "short")){
    
    # y range equals the point estimates 
    y_ran[[speciesgroup]][[type]] <- dat_trends_plot_list[[speciesgroup]] %>% 
      filter(Trend_type %in% type) %>% 
      pull(Perc_annual) %>%
      range(na.rm = TRUE)
    y_ran[[speciesgroup]][[type]] <- range(y_ran[[speciesgroup]][[type]], 0)
    
  sel <- dat_trends_plot_list[[speciesgroup]]$Trend_type %in% type
  dat_trends_plot_list[[speciesgroup]]$label_coor[sel] <- mean(y_ran[[speciesgroup]][[type]])

  }
}


gg_trends_list <- list(list(), list())

for (speciesgroup in speciesgroups){

  for (type in c("long", "short")){
    
    gg_trends_list[[speciesgroup]][[type]] <- ggplot(dat_trends_plot_list[[speciesgroup]] %>% filter(Trend_type %in% type), 
                                                     aes(x = Station, y = Perc_annual)) +
      geom_linerange(aes(ymin = Perc_annual_lo, ymax = Perc_annual_hi, colour = Trend_color), size = 1) +
      geom_point(aes(fill = Trend_color, shape = Trend_color), colour = "black", size = 3) +
      scale_colour_manual(values = trend_colours, drop = FALSE) +
      scale_fill_manual(values = trend_colours, drop = FALSE) +
      scale_shape_manual(values = trend_shapes, drop = FALSE) +
      geom_hline(yintercept = 0, color = "grey30") +
      geom_label(aes(y = label_coor, 
                     label = Trend_text), fill = "white", color = "blue3", 
                 label.size = 0, size = 3, hjust = 0.5) +
      coord_flip(ylim = y_ran[[speciesgroup]][[type]]) +
      labs(title = glue("Trend ({type}-term)"), y = "") +
      theme_bw() 
    
  }
  
}


if (FALSE){
  gg_trends_list[[1]][["long"]]
  gg_trends_list[[1]][["short"]]
  gg_trends_list[[2]][["long"]]
  gg_trends_list[[2]][["short"]]
}


```

```{r 06_combine_plots, fig.width=10, fig.height=8, warning=FALSE}

ggcomb_list <- list()

for (speciesgroup in speciesgroups){
  
  ggcomb_list[[speciesgroup]] <- cowplot::plot_grid(
    gg_tile_list[[speciesgroup]] + theme(legend.position = "none"), 
    gg_trends_list[[speciesgroup]][[1]] + 
      theme(axis.title.y = element_blank(),
            axis.text.y = element_blank(),
            legend.position = "none"), 
    gg_trends_list[[speciesgroup]][[2]] + 
      theme(axis.title.y = element_blank(),
            axis.text.y = element_blank()), 
    nrow = 1, ncol = 3,
    rel_heights = 3,
    rel_widths = c(2.7, 0.75, 1.25)
  )
  
  ggcomb_legend <- cowplot::get_legend(gg_tile_list[[speciesgroup]])
  
  # Set name of figure file (mercury in cod+birds is treated as a special case)
  if (params$basis_medians != params$basis_trends & speciesgroup == 1){
    filename <- glue::glue("Figures/431/{params$param}-{params$basis_medians}-{params$basis_trends}_combo_{speciesgroup}.png")
  } else {
    filename <- glue::glue("Figures/431/{params$param}_combo_{speciesgroup}.png")
  }
  
  # Save
  ggsave(filename, ggcomb_list[[speciesgroup]], width = 14, height = 8, dpi = 200)
    
  # Make and save legend
  filename <- glue::glue("Figures/431/_combo_legend.png")
  ggsave(filename, ggdraw(ggcomb_legend), width = 2, height = 4, dpi = 200)
  
}

# ggcomb_list[[1]]
# ggcomb_list[[2]]


```

```{r 05_trend_plot_legend}

# ggdraw(ggcomb_legend)

```

## Last year's concentrations (EQS + Proref ratio)       

```{r 06_ratio_data_1}  

#
# Cod + eider duck raw data
#

# Note: the 'current_year' in get_data_raw means "only series that includes current_year",
#   previous years are also included

dat_raw1 <- get_data_raw(params$param, "Gadus morhua", "Muskel", params$basis_medians, include_year=current_year)  
dat_raw2 <- get_data_raw(params$param, "Somateria mollissima", "Blod", "WW", include_year=current_year)
dat_raw3 <- get_data_raw(params$param, "Somateria mollissima", "Egg", "WW", include_year=current_year)  

dat_raw_codeider <- bind_rows(dat_raw1, dat_raw2, dat_raw3)

#
# Cod + eider duck median data
#
dat_to_add <- dat_raw_codeider %>%
  filter(MYEAR %in% current_year & !is.na(Value)) %>%
  group_by(PARAM, LATIN_NAME, TISSUE_NAME, STATION_CODE, Basis) %>%
  summarise(
    Value_lo = quantile(Value, probs = 0.25),                            # note: 1st and 3rd quartiles for cod + eider
    Value_lo = quantile(Value, probs = 0.25),                            # note: 1st and 3rd quartiles for cod + eider
    Value_hi = quantile(Value, probs = 0.75), .groups = "drop") 

dat_last_codeider <- dat_medians_list[[1]] %>%                           # 1 for cod + eider
  filter(MYEAR %in% current_year) %>%
  left_join(dat_to_add, by = c("PARAM", "LATIN_NAME", "TISSUE_NAME", "STATION_CODE", "Basis"))

# For sorting N to S, add
# mutate(Station = forcats::fct_rev(Station))

# Check that station codes are the same
st1 <- unique(dat_to_add$STATION_CODE) %>% sort()
st2 <- unique(dat_medians_list[[1]]$STATION_CODE) %>% sort()
if (!identical(st1,st2)){
  warning("Station codes are not identical")
}


```



```{r 06_ratio_data_2}  

#
# Blue mussel raw data
#

# debugonce(get_data_raw)  
dat_raw_mussel <- get_data_raw(params$param, "Mytilus edulis", "Whole soft body", "WW", current_year)  

#
# Blue mussel median data
#
dat_to_add <- dat_raw_mussel %>%
  filter(MYEAR %in% current_year & !is.na(Value)) %>%
  group_by(PARAM, LATIN_NAME, TISSUE_NAME, STATION_CODE, Basis) %>%
  summarise(
    Value_lo = min(Value),                             # note: min and max for blue mussel
    Value_hi = max(Value), .groups = "drop") %>%
  mutate(STATION_CODE = ifelse(STATION_CODE == "36A1", "36A", STATION_CODE))

dat_last_mussel <- dat_medians_list[[2]] %>%                           # 2 for blue mussel
  filter(MYEAR %in% current_year) %>%
  left_join(dat_to_add, by = c("PARAM", "LATIN_NAME", "TISSUE_NAME", "STATION_CODE", "Basis"))

st1 <- unique(dat_to_add$STATION_CODE) %>% sort()
st2 <- unique(dat_medians_list[[2]]$STATION_CODE) %>% sort()
if (!identical(st1,st2)){
  warning("Station codes are not identical")
}

if (FALSE){
  # Check station names in the two
  setdiff(st1,st2)
  setdiff(st2,st1)
  # dat_medians_list[[2]] %>% filter(STATION_CODE == "28A2") %>% View()
}

```


```{r 06_ratio_data_3}

dat_last_list <- list(
  dat_last_codeider,
  dat_last_mussel)

dat_raw_list <- list(
  dat_raw_codeider %>% 
    filter(MYEAR %in% current_year & !is.na(Value)),
  dat_raw_mussel %>% 
    filter(MYEAR %in% current_year & !is.na(Value)) %>% 
    mutate(STATION_CODE = ifelse(STATION_CODE == "36A1", "36A", STATION_CODE))
)



for (speciesgroup in speciesgroups){
  
  dat_last_list[[speciesgroup]] <- dat_last_list[[speciesgroup]] %>% 
    ungroup() %>%
    mutate(
      Proref_ratio_lo = Value_lo/Proref,
      Proref_ratio_hi = Value_hi/Proref,
      EQS_ratio_lo = Value_lo/EQS,
      EQS_ratio_hi = Value_hi/EQS,
      Proref_line = Proref/EQS,         # for adding extra line for proref
      Proref_tooltip = paste0(
        "Conc.: ", Value, " (Min-max: ", Value_lo, "-", Value_hi, ")\n",
        "Ratio: ", Proref_ratio, " (Min-max: ", Proref_ratio_lo, "-", Proref_ratio_hi, ")\n"),
      EQS_tooltip = paste0(
        "Conc.: ", Value, " (Min-max: ", Value_lo, "-", Value_hi, ")")
    ) %>%
    left_join(
      dat_trends_plot_list[[speciesgroup]] %>% 
        filter(Trend_type %in% "short") %>%
        select(PARAM, LATIN_NAME, TISSUE_NAME, STATION_CODE, Basis, Trend_color),
      by = c("PARAM", "LATIN_NAME", "TISSUE_NAME", "STATION_CODE")
    )
  
  sel <- is.na(dat_last_list[[speciesgroup]]$Trend_color)
  dat_last_list[[speciesgroup]]$Trend_color[sel] <- "No change"
  
  dat_raw_list[[speciesgroup]] <- dat_raw_list[[speciesgroup]] %>% 
    mutate(
      Proref_ratio = Value/Proref,
      EQS_ratio = Value/EQS,
      Proref_tooltip = paste0(
        "Conc.: ", Value, "\n",
        "Ratio: ", round(Proref_ratio, 3)),
      EQS_tooltip = paste0(
        "Conc.: ", Value, "\n",
        "Ratio: ", round(EQS_ratio, 3)),
    ) %>%
    # Add Station
    left_join(
      dat_last_list[[speciesgroup]] %>% 
        select(PARAM, LATIN_NAME, TISSUE_NAME, STATION_CODE, Station),
      by = c("PARAM", "LATIN_NAME", "TISSUE_NAME", "STATION_CODE")
    )
    
  
}

map_int(dat_last_list, nrow)
map_int(dat_raw_list, nrow)

```

```{r 07_eqsratio_plot, fig.width=8, fig.height=5.5}

if (params$eqsplot == TRUE){
  
  plot_eqsratio_list <- list()
  
  for (speciesgroup in speciesgroups){
    
    data_proref_medians <- dat_last_list[[speciesgroup]]
    data_proref_samples <- dat_raw_list[[speciesgroup]]
    
    # Order stations correctly
    data_proref_medians <- data_proref_medians %>%
      ungroup() %>%
      left_join(lookup_stations %>% select(STATION_CODE, Order), by = "STATION_CODE") %>%
      arrange(Order) %>%
      mutate(Station = forcats::fct_inorder(Station))
    data_proref_samples <- data_proref_samples %>%
      ungroup() %>%
      left_join(lookup_stations %>% select(STATION_CODE, Order), by = "STATION_CODE") %>% # View()
      arrange(Order) %>%
      mutate(Station = forcats::fct_inorder(Station))
    
    # Set plot title (mercury in cod+birds is treated as a special case)
    if (params$param %in% "HG" & speciesgroup == 1 & params$basis_medians == "WW"){
      plot_title <- paste0("EQS ratio, ", params$param, " (not length-adjusted) in ", speciesgroup_txt_proref[[speciesgroup]])
    } else if (params$param %in% "HG" & speciesgroup == 1 & params$basis_medians == "WWa"){
      plot_title <- paste0("EQS ratio, ", params$param, " (length-adjusted) in ", speciesgroup_txt_proref[[speciesgroup]])
    } else {
      plot_title <- paste0("EQS ratio, ", params$param, " in ", speciesgroup_txt_proref[[speciesgroup]])
    }
    
    if (params$ratioplot_trend == "TRUE"){
      
      gg <- ggplot(data_proref_medians, 
                   aes(Station, EQS_ratio)) +
        # The next line (median points) needs to be here (even if it is repeated after the sample points) to keep x order correct
        geom_point(aes(fill = Trend_color, shape = Trend_color), colour = "black", size = 3) +
        geom_point(data = subset(data_proref_samples, is.na(FLAG1)), color = "grey50", shape = 1, size = 2) +
        geom_point(data = subset(data_proref_samples, !is.na(FLAG1)), color = "grey50", shape = 6, size = 2) +
        geom_linerange(aes(ymin = EQS_ratio_lo, ymax = EQS_ratio_hi, colour = Trend_color), size = 1) +
        geom_point(aes(fill = Trend_color, shape = Trend_color), colour = "black", size = 3) +
        scale_colour_manual(values = trend_colours, drop = FALSE) +
        scale_fill_manual(values = trend_colours, drop = FALSE) +
        scale_shape_manual(values = trend_shapes, drop = FALSE) +
        geom_hline(yintercept = 1, color = "red2", linetype = "dashed") +
        annotate("text", x = -1.7, y = 1, label = "EQS", color = "red2", hjust = 0, vjust = -0.3) +
        coord_cartesian(xlim = c(-1.5, length(data_proref_medians$Station))) +
        labs(title = plot_title, 
             y = "Concentration/EQS") +
        theme_bw() +
        theme(legend.title = element_blank()) +
        ggeasy::easy_rotate_x_labels(angle = -45) 
      
    } else {
      
      gg <- ggplot(data_proref_medians, 
                   aes(Station, EQS_ratio)) +
        # The next line (median points) needs to be here (even if it is repeated after the sample points) to keep x order correct
        geom_point(colour = "black", size = 3) +
        geom_point(data = subset(data_proref_samples, is.na(FLAG1)), color = "grey50", shape = 1, size = 2) +
        geom_point(data = subset(data_proref_samples, !is.na(FLAG1)), color = "grey50", shape = 6, size = 2) +
        geom_linerange(aes(ymin = EQS_ratio_lo, ymax = EQS_ratio_hi), size = 1) +
        geom_point(colour = "black", size = 3) +
        geom_hline(yintercept = 1, color = "red2", linetype = "dashed") +
        annotate("text", x = -1.7, y = 1, label = "EQS", color = "red2", hjust = 0, vjust = -0.3) +
        coord_cartesian(xlim = c(-1.5, length(data_proref_medians$Station))) +
        labs(title = plot_title, 
             y = "Concentration/EQS") +
        theme_bw() +
        theme(legend.title = element_blank()) +
        ggeasy::easy_rotate_x_labels(angle = -45) 
      
    }
    
    # Add proref line on EQS plot
    proref <- data_proref_medians$Proref_line
    proref <- proref[!is.na(proref)][1]   # the first non-negative value
    gg <- gg +
      geom_hline(yintercept = proref, color = "blue2", linetype = "dashed") +
      annotate("text", x = -1.7, y = proref, label = "PROREF", color = "blue2", hjust = 0, vjust = -0.3)
    
    # Set name of figure file (mercury in cod+birds is treated as a special case)
    if (params$basis_medians != params$basis_trends & speciesgroup == 1){
      filename <- glue::glue("Figures/431/{params$param}-{params$basis_medians}-{params$basis_trend}_eqsratio_ord_{speciesgroup}.png")
    } else {
      filename <- glue::glue("Figures/431/{params$param}_eqsratio_ord_{speciesgroup}.png")
    }
    
    # Save
    ggsave(filename, gg, 
           width = 9, height = 6, dpi = 200)
    
    # Save again, but this time on log scale  
    filename <- sub("eqsratio_ord", "eqsratio_log", filename, fixed = TRUE)
    ggsave(filename, gg + scale_y_log10(), 
           width = 9, height = 6, dpi = 200)
    
    plot_eqsratio_list[[speciesgroup]] <- gg
    
  }
  
  
}


```



```{r 08_prorefratio_plot, fig.width=8, fig.height=5.5}

plot_prorefratio_list <- list()

for (speciesgroup in speciesgroups){

  data_proref_medians <- dat_last_list[[speciesgroup]]
  data_proref_samples <- dat_raw_list[[speciesgroup]]
  
  #  mutate(
  #    STATION_CODE = ifelse(STATION_CODE == "36A", "36A1", STATION_CODE)
  #  )

  if (speciesgroup == 1){
    # No Proref for the bird stations, so we delete them
    data_proref_medians <- data_proref_medians %>%
      filter(!Station %in% c("19N Kongsfjorden (eider duck blood)", "19N Kongsfjorden (eider duck egg)")) %>%
      mutate(Station = forcats::fct_drop(Station))
    data_proref_samples <- data_proref_samples %>%
      filter(!Station %in% c("19N Kongsfjorden (eider duck blood)", "19N Kongsfjorden (eider duck egg)")) %>%
      mutate(Station = factor(Station, levels = levels(data_proref_medians$Station)))
  }
  
  # Order stations correctly
  data_proref_medians <- data_proref_medians %>%
    ungroup() %>%
    left_join(lookup_stations %>% select(STATION_CODE, Order), by = "STATION_CODE") %>%
    arrange(Order) %>%
    mutate(Station = forcats::fct_inorder(Station))
  data_proref_samples <- data_proref_samples %>%
    # mutate( STATION_CODE = ifelse(STATION_CODE == "36A1", "36A", STATION_CODE)) %>%
    ungroup() %>%
    left_join(lookup_stations %>% select(STATION_CODE, Order), by = "STATION_CODE") %>% # View()
    arrange(Order) %>%
    mutate(Station = forcats::fct_inorder(Station))
  data_proref_samples_overLOQ <- data_proref_samples %>%
    filter(is.na(FLAG1))
  data_proref_samples_underLOQ <- data_proref_samples %>%
    filter(FLAG1 %in% "<")

  # Set plot title (mercury in cod+birds is treated as a special case)
  if (params$param %in% "HG" & speciesgroup == 1 & params$basis_medians == "WW"){
    plot_title <- paste0("Proref ratio, ", params$param, " (not length-adjusted) in ", speciesgroup_txt_proref[[speciesgroup]])
  } else if (params$param %in% "HG" & speciesgroup == 1 & params$basis_medians == "WWa"){
    plot_title <- paste0("Proref ratio, ", params$param, " (length-adjusted) in ", speciesgroup_txt_proref[[speciesgroup]])
  } else {
    plot_title <- paste0("Proref ratio, ", params$param, " in ", speciesgroup_txt_proref[[speciesgroup]])
  }
  
  gg <- ggplot(data_proref_medians, 
               aes(Station, Proref_ratio)) +
    # The next line (median points) needs to be here (even if it is repeated after the sample points) to keep x order correct
    geom_point(aes(fill = Trend_color, shape = Trend_color), colour = "black", size = 3) +
    geom_point(data = data_proref_samples_overLOQ , color = "grey50", shape = 1, size = 2) +
    geom_point(data = data_proref_samples_underLOQ , color = "grey50", shape = 6, size = 2) +
    geom_linerange(aes(ymin = Proref_ratio_lo, ymax = Proref_ratio_hi, colour = Trend_color), size = 1) +
    geom_point(aes(fill = Trend_color, shape = Trend_color), colour = "black", size = 3) +
    scale_colour_manual(values = trend_colours, drop = FALSE) +
    scale_fill_manual(values = trend_colours, drop = FALSE) +
    scale_shape_manual(values = trend_shapes, drop = FALSE) +
    geom_hline(yintercept = 1, color = "blue2", linetype = "dashed") +
    annotate("text", x = -1.7, y = 1, label = "PROREF", color = "blue2", hjust = 0, vjust = -0.3) +
    coord_cartesian(xlim = c(-1.5, length(data_proref_medians$Station))) +
    labs(title = plot_title,  
         y = "Concentration/PROREF") +
    theme_bw() +
    theme(legend.title = element_blank()) +
    ggeasy::easy_rotate_x_labels(angle = -45) 
  
  plot_prorefratio_list[[speciesgroup]] <- gg
  
  # Set name of figure file (mercury in cod+birds is treated as a special case)
  if (params$basis_medians != params$basis_trends & speciesgroup == 1){
    filename <- glue::glue("Figures/431/{params$param}-{params$basis_medians}-{params$basis_trend}_prorefratio_ord_{speciesgroup}.png")
  } else {
    filename <- glue::glue("Figures/431/{params$param}_prorefratio_ord_{speciesgroup}.png")
  }

  # Save  
  ggsave(filename, gg, 
         width = 9, height = 6, dpi = 200)
  
  # Save again, but this time on log scale  
  filename <- sub("prorefratio_ord", "prorefratio_log", filename, fixed = TRUE)
  ggsave(filename, gg + scale_y_log10(), 
         width = 9, height = 6, dpi = 200)
  

}


```
