---
title: "Report for parameter (430)"
author: "DHJ"
date: "18.08.2022"
params:
  param: "HG"
output: 
  html_document:
  keep_md: false
toc: true
toc_float: true
---

```{r, echo=FALSE}
knitr::opts_chunk$set(
  echo = FALSE, 
  results = 'hold',
  fig.width = 12)
```
   
```{r 01_settings}
current_year <- 2021
```

```{r 02_packages, results='hide', message=FALSE, warning=FALSE}

library(dplyr)
# library(tidyr)
library(ggplot2)
library(lubridate)
library(flextable)
# library(glue)
library(readxl)
library(purrr)
# library(leftcensored)   # DHJ's package (https://github.com/DagHjermann/leftcensored)
library(scico)            # colour palettes incl. "Vik" (https://github.com/thomasp85/scico)

library(ggiraph)
library(cowplot)

# library(safejoin) # https://github.com/moodymudskipper/safejoin

# source("01_Get_chemical_data_NIVAbasen_functions.R")  # for get_standard_parametername()
# source("824_Report_for_scientists_functions.R")
source("420_Report_paramgroup_functions.R", encoding = "UTF-8")

source("125_Calculate_trends_leftadjusted_functions.R")

```

```{r 03_get_data, warning=FALSE}

chem_params <- params$param

# debugonce(get_data_tables)
dat_list <- get_data_tables(param = params$param)

# str(dat_list, 1)

# Add min and max to 'dat_list$medians'  
df_min_max <- dat_list$data %>%
  select(PARAM, STATION_CODE, LATIN_NAME, TISSUE_NAME, MYEAR, VALUE_WW, VALUE_WWa) %>%
  tidyr::pivot_longer(cols = c(VALUE_WW, VALUE_WWa), names_to = "Basis", values_to = "Value") %>%
  mutate(Basis = sub("VALUE_", "", Basis, fixed = TRUE)) %>%
  group_by(PARAM, STATION_CODE, LATIN_NAME, TISSUE_NAME, Basis, MYEAR) %>%
  summarise(Value_min = min(Value, na.rm = TRUE),
            Value_max = max(Value, na.rm = TRUE), .groups = "drop"
            )

n1 <- nrow(dat_list$medians)
dat_list$medians <- dat_list$medians %>%
  left_join(df_min_max, by = c("MYEAR", "STATION_CODE", "LATIN_NAME", "TISSUE_NAME", "PARAM", "Basis"))
n2 <- nrow(dat_list$medians)

if (n2 != n1){
  stop("Check uniqueness")
}

# View(dat_list$data)
# View(dat_list$medians)
# View(dat_list$medians)
# View(dat_list$lookup_eqs)

```

```{r 04_medians_data}

species <- "Mytilus edulis"
tissue <- "Whole soft body"
basis <- "WW"

if (nrow(dat_list$lookup_eqs) == 1){
  dat_list$lookup_eqs$LATIN_NAME <- species
}

# Select data
dat_medians_01 <- dat_list$medians %>%
  filter(LATIN_NAME %in% species,
         TISSUE_NAME %in% tissue,
         Basis %in% "WW") %>%
  # Must have data in 'current_year'  
  group_by(STATION_CODE) %>%
  mutate(Series_last_year = max(MYEAR)) %>%
  filter(Series_last_year %in% current_year)

station_order <- dat_list$lookup_stations %>%
  filter(STATION_CODE %in% unique(dat_medians_01$STATION_CODE)) %>%
  mutate(Station = paste(STATION_CODE, Station_name)) %>%
  select(-Art) %>%
  arrange(Order)

dat_medians_02 <- dat_medians_01 %>%
  # Add EQS
  left_join(dat_list$lookup_eqs, 
            by = c("LATIN_NAME", "PARAM", "Basis"))

dat_medians_03 <- dat_medians_02 %>%
  # Add station name
  left_join(
    dat_list$lookup_stations %>% 
      filter(LATIN_NAME %in% species) %>%
      select(STATION_CODE, LATIN_NAME, Station_name, Region),
    by = "STATION_CODE"
  ) %>%
  mutate(
    Station = factor(
      paste(STATION_CODE, Station_name),
      levels = rev(station_order$Station)),
    Proref_ratio = Value/Proref,
    EQS_ratio = Value/EQS,
    Above_EQS = case_when(
      Value > EQS ~ "Over",
      Value <= EQS ~ "Under",
      TRUE ~ as.character(NA)),
    Prop_underLOQ = 1 - Over_LOQ/N_median,
    FLAG1 = case_when(
      Prop_underLOQ < 0.5 ~ as.character(NA),
      Prop_underLOQ >= 0.5 ~ "<"),
    LOQ_label = ifelse(Prop_underLOQ >= 0.5, "<", "")
  ) %>%
  filter(!is.na(Station))

# Add 'Proref_ratio_cut'  
proref_max <- max(dat_medians_03$Proref_ratio, na.rm = TRUE)
dat_medians <- dat_medians_03 %>%
  mutate(
    Proref_ratio_cut = cut(Proref_ratio, breaks = c(0,0.5,0.75,0.9,1,2,3,5,10, proref_max))
  )

# ggplot(dat_medians, aes(MYEAR, Station, fill = Proref_ratio_cut)) +
#   geom_tile()

```

## Medians

```{r 04_medians_plot, fig.width = 10, fig.height=11}

proref_cols <- c(RColorBrewer::brewer.pal(6, "Blues")[5:2],
            RColorBrewer::brewer.pal(6, "YlOrRd")[1:5])
  
# col_func <- function(x){cols[x]}

startyr <- 2010

no_eqs <- mean(is.na(dat_medians$EQS_ratio)) == 1

if (no_eqs){
  dat_medians2 <- dat_medians %>% filter(MYEAR >= 2010) %>%
    mutate(
      Value_txt = paste0(
        "Proref ratio: ", round(Proref_ratio, 3), "<br>",
        "Median: ", LOQ_label, round(Value, 4), " ug/kg<br>",
        "(", round(Value_min, 4), "-", round(Value_max, 4), "; N =", N_median, ")")
    )
} else {
  dat_medians2 <- dat_medians %>% filter(MYEAR >= 2010) %>%
    mutate(
      Value_txt = paste0(
        "Proref ratio: ", round(Proref_ratio, 3), "<br>",
        "EQS ratio: ", round(EQS_ratio, 3), "<br>",
        "Median: ", LOQ_label, round(Value, 4), " ug/kg<br>",
        "(", round(Value_min, 4), "-", round(Value_max, 4), "; N =", N_median, ")")
    )
}

gg_tile <- ggplot(dat_medians2, aes(MYEAR, Station, label = round(Value, 3))) +
  geom_tile(aes(fill = Proref_ratio_cut)) + 
  geom_tile(data = subset(dat_medians2, Above_EQS %in% "Over"),
            color = "red", size = 1, height = 0.9, width = 0.9, alpha = 0) +
  scale_fill_manual("Proref\nratio", values = proref_cols) +
  scale_color_manual(values = c("red", "white")) +
  scale_alpha_manual(values = c(1, 0)) +
  geom_text(aes(label = LOQ_label), size = 3, nudge_y = 0.3) +
  geom_text_interactive(aes(tooltip = Value_txt), nudge_y = -0.1, size = 3) +
  scale_x_continuous(breaks = seq(startyr, 2020, 2), 
                     limits = c(startyr-0.5, current_year+0.5)) +
  theme_bw() +
  guides(colour = "none") +
  labs(
    title = paste0(params$param, " in ", species, " (", tissue, ")"),
    x = "Year", y = "")

girafe(ggobj = gg_tile, height_svg = 5.7, width_svg = 9)

```

```{r 05_trend_data1}

# check <- readRDS("Data/126_df_trend_2021.rds")
# table(check$Trend_string)

dat_trends <- readRDS("Data/126_df_trend_2021.rds") %>%
  filter(PARAM %in% params$param)

# table(dat_trends$Trend_string)

# Keep only actual trends
# dat_trends <- dat_trends_all %>%
#   filter(Trend_string %in% c("Increasing", "Decreasing", "No change"))

```



```{r 05_trend_data2}

# * The difference between 'No change' and 'No trend' is very subtle (see script 126):   
#    - 'No change' means that there is a time trend, but no difference between the two actual years compared  
#    - 'No trend' means that there is no time trend (the best model was y = constant)   
# * So we combine the two  

shape_order <- c("Increasing", "Decreasing", "No change")
colour_order <- shape_order

dat_trends_plot <- dat_trends %>%
  filter(LATIN_NAME %in% species,
         TISSUE_NAME %in% tissue) %>%
  # Add station name
  left_join(
    dat_list$lookup_stations %>% 
      select(STATION_CODE, Station_name),
    by = "STATION_CODE"
  ) %>%
  mutate(
    Station = factor(
      paste(STATION_CODE, Station_name),
      levels = rev(station_order$Station)),
    # Shape and colour: Drop "Too few over-LOQ years" and "Too few years:
    Trend_shape = case_when(
      Trend_string %in% c("Increasing" , "Decreasing", "No change") ~ Trend_string, 
      Trend_string %in% c("No trend") ~ "No change", 
      TRUE ~ as.character(NA)),
    Trend_shape = factor(Trend_shape, levels = shape_order),
    Trend_color = Trend_shape,
    # Text: Keep only "Too few over-LOQ years" and "Too few years:
    Trend_text = case_when(
      Trend_string %in% c("Increasing" , "Decreasing", "No change", "No trend") ~ "", 
      TRUE ~ Trend_string),
    Perc_annual = case_when(
      Trend_string %in% c("No change", "No trend") ~ 0, 
      TRUE ~ Perc_annual),
    Trend_shape = factor(Trend_shape, levels = shape_order)
  )

y_ran <- range(dat_trends_plot$Perc_annual, na.rm = TRUE)

```


## Trends (long- and short-term)  

```{r 05_trend_plot, warning=FALSE}

trend_shapes <- c(24, 25, 21) %>% setNames(shape_order)
trend_colours <- c("red2", "green4", "grey20") %>% setNames(colour_order)
trend_fill <- c("red2", "green4", "grey20") %>% setNames(colour_order)

dat_trends_plot <- dat_trends_plot %>%
  mutate(
    Tooltip_text = case_when(
      Trend_string %in% c("Increasing", "Decreasing") ~ 
        paste0(
          "Trend (", Trend_type, "-term) :" , round(Perc_annual,2), " % (", First_year, "-", current_year, ")\n",
          "Change since ", First_year, ": ", Perc_change, " % (", p_category, ")\n", 
          "Trend model: ", ifelse(k_sel >= 3, paste("Non-linear (k = ", k_sel, ")"), "Linear")
        ),
      TRUE ~ Trend_string
    )
  )

trendtype <- "long"

gg_range <- ggplot(dat_trends_plot %>% filter(Trend_type %in% trendtype),
       aes(x = Station, y = Perc_annual)) +
  geom_text(aes(y = 0, label = Trend_text)) +                                                # For "too few years etc.
  geom_linerange(aes(ymin = Perc_annual_lo, ymax = Perc_annual_hi, colour = Trend_color)) +
  geom_hline(yintercept = 0) +
  geom_point_interactive(aes(colour = Trend_color, fill = Trend_color, shape = Trend_color, tooltip = Tooltip_text)) +
  scale_colour_manual(values = trend_colours, drop = FALSE) +
  scale_fill_manual(values = trend_colours, drop = FALSE) +
  scale_shape_manual(values = trend_shapes, drop = FALSE) +
  coord_flip(ylim = y_ran) +
  theme_bw() +
  labs(
    title = stringr::str_to_sentence(paste0(trendtype, "-term trend"))
  )

girafe(ggobj = gg_range, height_svg = 5.7, width_svg = 9)

trendtype <- "short"

gg_range <- ggplot(dat_trends_plot %>% filter(Trend_type %in% trendtype),
       aes(x = Station, y = Perc_annual)) +
  geom_text(aes(y = 0, label = Trend_text)) +                                                # For "too few years etc.
  geom_linerange(aes(ymin = Perc_annual_lo, ymax = Perc_annual_hi, colour = Trend_color)) +
  geom_hline(yintercept = 0) +
  geom_point_interactive(aes(colour = Trend_color, fill = Trend_color, shape = Trend_color, tooltip = Tooltip_text)) +
  scale_colour_manual(values = trend_colours, drop = FALSE) +
  scale_fill_manual(values = trend_colours, drop = FALSE) +
  scale_shape_manual(values = trend_shapes, drop = FALSE) +
  coord_flip(ylim = y_ran) +
  theme_bw() +
  labs(
    title = stringr::str_to_sentence(paste0(trendtype, "-term trend"))
  )

girafe(ggobj = gg_range, height_svg = 5.7, width_svg = 9)


```


```{r 07_ratios_data}

region_order <- c("Viken og Oslo", "Vestfold og Telemark", "Agder", "Vestland", "Møre og Romsdal", 
                  "Trøndelag", "Nordland", "Troms og Finnmark", "Svalbard")

dat_medians_lastyear <- dat_medians %>% 
  ungroup() %>%
  filter(MYEAR == current_year) %>%
  mutate(
    Proref_ratio_min = Value_min/Proref,
    Proref_ratio_max = Value_max/Proref,
    EQS_ratio_min = Value_min/EQS,
    EQS_ratio_max = Value_max/EQS,
    Proref_tooltip = paste0(
      "Conc.: ", Value, " (Min-max: ", Value_min, "-", Value_max, ")\n",
      "Ratio: ", round(Proref_ratio, 2), " (Min-max: ", round(Proref_ratio_min, 2), "-", round(Proref_ratio_max, 2), ")\n"),
    EQS_tooltip = paste0(
      "Conc.: ", Value, " (Min-max: ", Value_min, "-", Value_max, ")\n",
      "Ratio: ", round(EQS_ratio, 2), " (Min-max: ", round(EQS_ratio_min, 2), "-", round(EQS_ratio_min, 2), ")\n"),
    Station = factor(Station, levels = rev(levels(Station))),
    Region = factor(Region, levels = rev(region_order))
  ) 


```


## Proref ratio  

```{r 07_ratios_proref, warning=FALSE}

ratioplot_interactive(data = dat_medians_lastyear,
          x = "Station", y = "Proref_ratio", fill = "Region", 
          tooltip = "Proref_tooltip", data_id = "STATION_CODE",
          ymin = "Proref_ratio_min", ymax = "Proref_ratio_max")  

```


## EQS ratio  

```{r 07_ratios_eqs, warning=FALSE}

ratioplot_interactive(data = dat_medians_lastyear,
                      x = "Station", y = "EQS_ratio", fill = "Region", 
                      tooltip = "EQS_tooltip", data_id = "STATION_CODE",
                      ymin = "EQS_ratio_min", ymax = "EQS_ratio_max")  

```


## All time series   

```{r 08_plotly_load, include=FALSE}

options(warn=-1)
library(plotly)
options(warn=0)

```

```{r 08_timeseries}

dat <- dat_list$data %>%
  filter(LATIN_NAME %in% species,
         TISSUE_NAME %in% tissue)

p <- ggplot(data = dat_medians, aes(x = MYEAR, y = Value, color = Station)) +
  geom_line() +
  geom_point() +
  scale_y_log10()

ggplotly(p)

# File size: 1.0 MB including ploty
# File size: 4.6 MB including ploty

```
