---
title: "Report for parameter (431)"
author: "NIVA"
params:
  param: "CD"
  basis_medians: "WW"
  basis_trends: "WW"
  eqsplot: "FALSE"
  prorefplot: "TRUE"
  include_trend: "TRUE"
  current_year: 2023
  called_from_mother: "TRUE"
  species3: "Mytilus edulis"
  conc_unit: "mg/kg wet weight"
output: 
  html_document:
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: console
---

```{r, include=FALSE}

#
# This file is run in three ways
#   1. (the intended way) by knitting one of the .Rmd files in '434_paramgroups' (called_from_mother: "TRUE")  
#   2. (for testing) by knitting this file itself (called_from_mother: "FALSE")  
#   3. (for testing) by running interactively, e.g. "Run all" (run_interactively = TRUE)  

run_interactively <- TRUE  
# run_interactively <- FALSE  

# Parameters:

# 'eqsplot' 
#  = "ordinary" or "TRUE" for ordinary y scale (TRUE is included for backwards compability)
#  = "log" for log y scale (with y labels showing true values)

# Chunks (nov. 2023):
#  1 -  3: Set up
#  4 -  6: Make tile plot of median concentrations (by stations x years)  
#  7 -  9: Make point/range plot of trends (2 plots for long and short term, by stations)  
# 10 - 15: Combine tile plot and point/range plot  
# 16 - 19: Get raw concentrations and ratios (EQS and proref) for last year    
# 20 - 23: EQS plots (by station)  
# 24 - 27: Proref plots (by station)  

#
# Data sources
#
# (functions referred to below are in script '431_Report_parameter_functions.R')
#
# Medians: 
#  Given by 'folder_110' and 'filename_110' in function 'get_data_medians'
#   default values are "Data" and "110_mediandata_updated_2022-09-23.rds"
# Trends: 
#   Given by 'filename_trends' in 'get_data_trends'   
#   default value is "Data/125_results_2021_07_output/126_df_trend_2021.rds"
# Raw data: 
#   Given by 'filename_109' in 'get_data_raw'  
#   default value is "Data/109_adjusted_data_2022-09-23.rds"

# the trend file needs the following columns:
# - series identifiers: PARAM, LATIN_NAME, TISSUE_NAME, STATION_CODE, Basis (WW or WWa)
# - Trend_type ("long", "short"), last_year, first_year  
# - Trend_string ("Increasing" , "Decreasing", "No change", "Estimation failed")
#   - other possible (but not necessary) values: "No trend", "Too few over-LOQ years", 
#     "Too few years", "No data before 20xx" and NA  
# - y_mean, y_q2.5, y_q97.5 - change (last_year to first_year) on natural log scale  

library(dplyr)

filename_109 <- "Data/109_adjusted_data_ELU_2024-09-25.rds"           # update
filename_110 <- "Data/110_mediandata_updated_ELU_2024-09-25.rds"      # update
filename_trends <- "Data/milkys4_01_trends_03.rds"            # update

lookup_ices_params <- bind_rows(
  data.frame(
    PARAM =       c("MBT",   "TPhT",  "DPhT",  "TBT",   "DBT"),
    determinand = c("MPSN+", "TPSN+", "DPSN+", "TBSN+", "DBSN+")),
  data.frame(
    PARAM =       c("BDE100", "BDE119", "BDE126", "BDE138", "BDE153", "BDE154", "BDE183", "BDE190", "BDE209"),
    determinand = c("BD100",  "BD119",  "BD126",  "BD138",  "BD153",  "BD154",  "BD183",   "BD190", "BD209")),
  data.frame(
    PARAM =       c("sumPCB6", "sumPCB7", "sumBDE", "sumHBCD", "sumHCH", "sumPAH15", "sumPAH16"),
    determinand = c(   "SCB6",    "SCB7",  "SBDE6",    "HBCD",    "HCH",   "SPAH15",   "SPAH16"))
)

lookup_trend <- data.frame(
  trend = c("upward trend", "downward trend", "no trend", "status assessment only", "informal status assessment"),
  Trend_string = c("Increasing", "Decreasing", "No change", "Too few years", "Too few years")
)

lookup_tissue <- data.frame(
  matrix = c("LI", "SB", "BL", "MU"),
  TISSUE_NAME = c("Lever", "Whole soft body", "Blod", "Muskel")
)

lookup_trendtype <- data.frame(
  trend_length = c("recent", "whole"),
  Trend_type = c("short", "long")
)

if (FALSE){
  
  # for 2023 data, using trend results from milkys5 script 01
  # needs to be done only every time the trend file is updated
  
df_trend_orig <- bind_rows(
  readr::read_csv("Data/milkys4_01_trends.csv"),
  readr::read_csv("Data/milkys4_01_trends_Hg-lengthadjusted.csv") #  %>% unique(determinand)
)

# dput(unique(df_trend_orig$matrix))
# table(df_trend_orig$matrix, df_trend_orig$determinand)
# table(df_trend_orig$matrix, df_trend_orig$species)
# table(df_trend_orig$station_name)
# table(df_trend_orig$trend_length)

df_trend <- df_trend_orig %>%
  left_join(
    lookup_ices_params, by = "determinand") %>%
  left_join(
    lookup_trend, by = "trend") %>%
  left_join(
    lookup_tissue, by = "matrix") %>%
  left_join(
    lookup_trendtype, by= "trend_length") %>%
  mutate(
    PARAM = case_when(
      determinand %in% "HG.lenadj" ~ "HG",
      is.na(PARAM) ~ determinand,
      TRUE ~ PARAM),
    STATION_CODE = stringr::str_extract(station_name, "[^\\s]+"),
    Basis = case_when(
      determinand %in% "HG.lenadj" ~ "WWa",
      TRUE ~ "WW"),
    y_mean = estimate,
    y_q2.5 = estimate - 2*se,
    y_q97.5 = estimate + 2*se) %>%
  rename(
    LATIN_NAME = species,
    first_year = start,
    last_year = end
  ) %>%
  select(
    series, PARAM, LATIN_NAME, TISSUE_NAME, STATION_CODE, Basis, 
    Trend_type, last_year, first_year, Trend_string,
    y_mean, y_q2.5, y_q97.5
  )

# Fix accidental duplicates of trend data
df_trend2 <- df_trend %>%
  arrange(PARAM, LATIN_NAME, TISSUE_NAME, STATION_CODE, Basis,
           Trend_type, Trend_string, first_year, last_year, y_mean, y_q2.5, y_q97.5) %>%
  group_by(PARAM, LATIN_NAME, TISSUE_NAME, STATION_CODE, Basis,
           Trend_type, Trend_string, first_year, last_year, y_mean, y_q2.5, y_q97.5) %>%
  mutate(i = 1:length(PARAM)) %>%
  filter(i == 1) %>%
  select(-i)

saveRDS(df_trend2, filename_trends)

}  

dat_groups <- read.csv("Input_data/Lookup_tables/Lookup table - substance groups.csv")  
header_param <- subset(dat_groups, PARAM %in% params$param, select = Parameter.Name)[1,1]

if (run_interactively){   # set to TRUE for running interactively, otherwise FALSE
  
  # Note that 'called_from_mother' = "NA" (see chunk 15)
  params <- list(param = "CD", basis_medians = "WW", basis_trends = "WW", 
                 eqsplot = "FALSE", prorefplot = "TRUE", include_trend = "TRUE", 
                 current_year = 2023, called_from_mother = "NA", 
                 species3 = "Mytilus edulis")
}

```


# `r header_param`  
   
```{r, include=FALSE}

# 01_settings

current_year <- params$current_year
knitr::opts_chunk$set(echo = FALSE, results = 'hold', warning = FALSE)

```

<style type="text/css">
div.main-container {
  max-width: 1800px;
  margin-left: auto;
  margin-right: auto;
}
</style>


```{r, include=FALSE}

# 02_packages

library(ggiraph)

library(ggplot2)
library(lubridate)
library(flextable)
# library(glue)
library(readxl)
library(purrr)
library(glue)
# library(leftcensored)   # DHJ's package (https://github.com/DagHjermann/leftcensored)
library(scico)            # colour palettes incl. "Vik" (https://github.com/thomasp85/scico)

library(cowplot)

# library(safejoin) # https://github.com/moodymudskipper/safejoin

source("431_Report_parameter_functions.R")
source("002_Utility_functions.R")

```

## Medians and trends    

```{r, warning=FALSE, message=FALSE}

# 03_medians_data1

library(dplyr)    # need to load dplyr AFTER ggiraph fro some reason, otherwise error "%>% is not found" 

#
# Get data 
#

species3 <- strsplit(params$species3, split = ",")[[1]]

# debugonce(get_data_medians)

# For server part in Shiny
dat_temporary <- list(
  # Cod
  get_data_medians(param = params$param,     # In Shiny: input$param
                   species = "Gadus morhua",
                   tissue = ifelse(params$param %in% "HG", "Muskel", "Lever"),
                   basis = params$basis_medians, 
                   include_year = params$current_year-1,
                   filename_110 = filename_110),
  # Eider duck
  get_data_medians(param = params$param, 
                   species = "Somateria mollissima",
                   tissue = "Blod",
                   basis = "WW", 
                   include_year = params$current_year-1,
                   filename_110 = filename_110),
  # Eider duck
  get_data_medians(param = params$param, 
                   species = "Somateria mollissima",
                   tissue = "Egg",
                   basis = "WW", 
                   include_year = params$current_year-1,
                   filename_110 = filename_110),
  # Blue mussel  
  get_data_medians(param = params$param, 
                   species = species3,
                   tissue = "Whole soft body",
                   basis = "WW", 
                   include_year = params$current_year-1,
                   filename_110 = filename_110)
)


# levels(dat_temporary[[1]]$Station)
# levels(dat_temporary[[2]]$Station) 

#
# Stations - for corrrect ordering
#
lookup_stations <- read.csv("Input_data/Lookup_tables/Lookup_stationorder.csv") # %>%


```

```{r}

# 03_medians_data2

library(purrr)
library(ggplot2)
library(glue)
library(cowplot)

#
# Combine cod and eider duck as one group  
#

eider_blood <- "19N Kongsfjorden (eider duck blood)"
eider_egg <- "19N Kongsfjorden (eider duck egg)"

#
# Make 'dat_medians_list'  
#

dat_medians_list <- list()

# List element 1: cod and eider duck

if (nrow(dat_temporary[[2]]) > 0){
  dat_medians_list[[1]] <- bind_rows(
    dat_temporary[[1]],
    dat_temporary[[2]] %>% mutate(Station = eider_blood),
    dat_temporary[[3]] %>% mutate(Station = eider_egg)
  )
} else {
  dat_medians_list[[1]] <- dat_temporary[[1]]
}

dat_medians_list[[1]]$Station <- factor(dat_medians_list[[1]]$Station, 
                                        levels = c(levels(dat_temporary[[1]]$Station), eider_blood, eider_egg))

# For Hg: add an asterisk after station names for stations that are NOT length-adjusted (for Hg only)
# - these data are also used for 'ratio plots' (last year's concentrations)  
if (params$param %in% "HG" & params$basis_medians %in% "WWa"){
  # View(dat_medians_list[[1]])
  tab <- xtabs(~Basis + Station, dat_medians_list[[1]])
  not_length_adjusted <- colnames(tab)[tab[2,] == 0]
  sel <- levels(dat_medians_list[[1]]$Station) %in% not_length_adjusted
  levels(dat_medians_list[[1]]$Station)[sel] <- paste(levels(dat_medians_list[[1]]$Station)[sel], "*")
}


# levels(dat_medians_list[[1]]$Station)

# List element 2 = blue mussel

dat_medians_list[[2]] <- dat_temporary[[4]]

# Check number of rows for cod/birds and blue mussel:
# map(dat_medians_list, nrow)

```


```{r, fig.width=10, fig.height=8, warning=FALSE}

# 04_medians_plot

proref_cols <- c(RColorBrewer::brewer.pal(6, "Blues")[5:2],
                 RColorBrewer::brewer.pal(6, "YlOrRd")[1:5])

col_func <- function(x){cols[x]}

startyr <- 2012
# Trick to avoid red frames also in legend:
# - put 'fill = Proref_ratio_cut' in aes of the first geom_tile (not in the aes of ggplot)
# - set 'alpha = 0' so there is no fill in the EQS tiles 

gg_tile_list <- list()

speciesgroup_txt <- c("cod and eider duck", "blue mussel")
speciesgroup_txt_proref <- c("cod", "blue mussel")

for (speciesgroup in 1:2){
  
  if (nrow(dat_medians_list[[speciesgroup]]) > 0){
    
    dat_medians <- dat_medians_list[[speciesgroup]] %>%
      mutate(
        Value_txt = case_when(
          is.na(FLAG1) ~ signif2(Value, 2, maxdigits = 5),
          !is.na(FLAG1) & Value > 0 ~ paste0("<", signif2(Value, 2, maxdigits = 4)),
          !is.na(FLAG1) & Value == 0 ~ "0"                                # for 'SCCP eksl. LOQ' + 'MCCP eksl. LOQ'
          ),
        txt_conc = paste0("Median value: ", Value_txt, 
                                   " (", signif(Value_min, 2), "-", signif(Value_max, 2), "; N =", N_median, ")"),
        txt_perc = paste0("25% and 75% percentiles: ", signif(Value_p25, 2), "-", signif(Value_p75, 2)),
        txt_loq = paste0("Measurements over LOQ: ", Over_LOQ, 
                                   " (", signif(100*(Over_LOQ/N_median), 1), " %); median LOQ = ", Det_limit),
        txt_eqs = paste0("The median is ", signif(EQS_ratio, 2), " times the EQS (", EQS, ")"),
        txt_proref = paste0("The median is ", signif(Proref_ratio, 2), " times the PROREF (", Proref, ")"),
        Tooltip_txt = txt_conc,
        Tooltip_txt = ifelse(N_median > 5, paste(Tooltip_txt, "<br>", txt_perc), Tooltip_txt),
        Tooltip_txt = ifelse(Over_LOQ < N_median, paste(Tooltip_txt, "<br>", txt_loq), Tooltip_txt),
        Tooltip_txt = ifelse(!is.na(EQS), paste(Tooltip_txt, "<br>", txt_eqs), Tooltip_txt),
        Tooltip_txt = ifelse(!is.na(Proref), paste(Tooltip_txt, "<br>", txt_proref), Tooltip_txt)
        )

    

    # Set plot title (mercury in cod+birds is treated as a special case)
    if (params$param %in% "HG" & speciesgroup == 1 & params$basis_medians == "WW"){
      plot_title <- paste0(dat_medians$Parameter.Name[1], " (not length-adjusted) in ", speciesgroup_txt[[speciesgroup]])
    } else if (params$param %in% "HG" & speciesgroup == 1 & params$basis_medians == "WWa"){
      plot_title <- paste0(dat_medians$Parameter.Name[1], " (length-adjusted) in ", speciesgroup_txt[[speciesgroup]])
    } else {
      plot_title <- paste0(dat_medians$Parameter.Name[1], " in ", speciesgroup_txt[[speciesgroup]])
    }
    
    gg_tile_list[[speciesgroup]] <- ggplot(dat_medians, aes(MYEAR, Station)) +
      geom_tile(aes(fill = Proref_ratio_cut)) + 
      geom_tile(data = subset(dat_medians, Above_EQS %in% "Over"),
                color = "red", size = 1, height = 0.9, width = 0.9, alpha = 0) +
      geom_text_interactive(aes(label = Value_txt, tooltip = Tooltip_txt), nudge_y = 0, size = 3) +
      # geom_text(aes(label = LOQ_label), size = 3, nudge_y = 0.3) +
      scale_fill_manual("Proref ratio", values = proref_cols, na.value = "grey85") +
      scale_color_manual(values = c("red", "white")) +
      scale_alpha_manual(values = c(1, 0)) +
      scale_x_continuous(breaks = seq(startyr, 2020, 2), 
                         limits = c(startyr-0.5, current_year+0.5)) +
      theme_bw() +
      guides(colour = "none") +
      labs(
        title = plot_title,
        x = "Year", y = "")
    
  } else {
    
    gg_tile_list[[speciesgroup]] <- NULL
    
  }
  
}

if (FALSE){
  gg_tile_list[[1]]
  gg_tile_list[[2]]
  girafe(ggobj = gg_tile_list[[1]], height_svg = 5.7, width_svg = 9)
  
  # Special case: SCCP and MCCP (eksl. LOQ)
  width_tileplot_only <- 2.7 / (2.7 + 0.75 + 1.25)
  for (speciesgroup in 1:2){
    filename <- glue::glue("Figures/431/{params$param}_combo_{speciesgroup}.png")
    # ggsave(filename, gg_tile_list[[speciesgroup]], width = 14*width_tileplot_only, height = 8, dpi = 200)
  }
  
}

```

```{r}

# 05_trends_settings

shape_order <- c("Increasing", "Decreasing", "No change")
colour_order <- shape_order
  
trend_shapes <- c(24, 25, 21) %>% setNames(shape_order)
trend_colours <- c("red3", "green4", "grey20") %>% setNames(colour_order)
trend_fill <- c("red2", "green2", "grey20") %>% setNames(colour_order)

```



```{r}

# 05_trends_data


dat_trends_plot_list <- purrr::map(
  dat_medians_list, 
  get_data_trends, basis = params$basis_trends, include_year = current_year-1,
  filename_trends = filename_trends
)

# debugonce(get_data_trends)
chck <- get_data_trends(dat_medians_list[[1]],  basis = "WW",
                        include_year = current_year, filename_trends = filename_trends)
# chck <- get_data_trends(dat_medians_list[[2]],  basis = "WW", 
#                         include_year = current_year, filename_trends = filename_trends)

# table(addNA(dat_trends_plot_list[[1]]$Station))
# levels(dat_trends_plot_list[[1]]$Station)
# View(dat_trends_plot_list[[1]])

# Check number of rows for cod/birds and blue mussel:
# map(dat_trends_plot_list, nrow)

# Series where QA shows that the trend is suspect, and alternative method has been used, 
#   namely cencorreg() in package NADA2, see script 451_cencorreg.qmd  
# Revised trend (text): Trend.QA
dat_trends_manual <- read.csv("Data/434_manual_trends/100_dat_trend 19oktober2023.txt") %>%
  filter(QA.different %in% "yes") %>%
  select(PARAM, STATION_CODE, TISSUE_NAME, LATIN_NAME, Basis, Trend_type, QA.different, Trend.QA) %>%
  mutate(Trend.QA = paste(Trend.QA, "*"))

# For explanatory text below plot (shown only if there are suspect trends)
text_trends_manual <- list(NA, NA)


```

```{r}

# 05_trends_create_plots

# Which species groups do we have? 
if (is.null(dat_trends_plot_list[[1]])){
  speciesgroups <- 2 
} else if (is.null(dat_trends_plot_list[[2]])){
  speciesgroups <- 1 
} else {
  speciesgroups <- 1:2
}

if (params$include_trend == "TRUE"){

#
# Two things happens here: 
# 1) Store y range in a list (used to set limits), and 
# 2) add label coordinate (label_coor) to the data 
# - needed because the label coordinate is inside aes()  
# - when we didn't do this, the label of plot no. 1 was ok after making plot.no. 1, but
#   moved as we made plots no. 2,3,4.... :-o
#


y_ran <- list(list(), list())

for (speciesgroup in speciesgroups){
  
  dat_trends_plot_list[[speciesgroup]] <- dat_trends_plot_list[[speciesgroup]] %>%
    mutate(
      Tooltip_txt = paste0(
        ifelse(Trend_type == "short", "10-year trend: ", "Long-term trend: "), Trend_string),
      Tooltip_txt = ifelse(
        Trend_string %in% c("Decreasing", "Increasing"),
        paste0(Tooltip_txt, "<br>Change per year: ", sprintf("%.1f", Perc_annual), 
              "% (conf.int.: ", round(Perc_annual_hi,1), " - ", round(Perc_annual_lo,1), ")"),
        Trend_string
        )
    )

  dat_trends_plot_list[[speciesgroup]]$label_coor <- NA

  for (type in c("long", "short")){
    
    # y range equals the point estimates 
    y_ran[[speciesgroup]][[type]] <- dat_trends_plot_list[[speciesgroup]] %>% 
      filter(Trend_type %in% type) %>% 
      pull(Perc_annual) %>%
      range(na.rm = TRUE)
    y_ran[[speciesgroup]][[type]] <- range(y_ran[[speciesgroup]][[type]], 0)
    
  sel <- dat_trends_plot_list[[speciesgroup]]$Trend_type %in% type
  dat_trends_plot_list[[speciesgroup]]$label_coor[sel] <- mean(y_ran[[speciesgroup]][[type]])

  }
}


gg_trends_list <- list(list(), list())

for (speciesgroup in speciesgroups){

  for (type in c("long", "short")){
    
    tab <- table(dat_medians_list[[speciesgroup]]$Station)
    station_levels <- names(tab)
    station_levels <- station_levels[tab != 0]
    data_for_plot <- dat_trends_plot_list[[speciesgroup]] %>% 
      filter(Trend_type %in% type) %>%
      mutate(Station = factor(Station, levels = station_levels))
    # For series where QA shows suspect trends and alternative method shows different result 
    #   (QA.different = 'yes'), clear data for trend estimates (Perc_annual etc.) and
    #   change Trend_text to Trend.QA 
    data_for_plot <- data_for_plot %>%
      left_join(dat_trends_manual, 
                by = join_by(PARAM, STATION_CODE, LATIN_NAME, TISSUE_NAME, Trend_type, Basis),
                relationship = "many-to-one")
    sel <- !is.na(data_for_plot$QA.different)
    if (sum(sel) > 0){
      for (colname in c("Perc_annual", "Perc_annual_lo", "Perc_annual_hi")){
        data_for_plot[[colname]][sel] <- NA  }
      data_for_plot[["Trend_text"]][sel] <- data_for_plot[["Trend.QA"]][sel]
      text_trends_manual[[speciesgroup]] <- "Asterisk (*) after trend text: Time trend test was performed with alternative trend method"
    }
    trendtitle_asterisk <- ifelse(params$basis_medians == "WW" & params$basis_trends == "WWa" & speciesgroup == 1, "*", "")
    gg_trends_list[[speciesgroup]][[type]] <- ggplot(
      data_for_plot, aes(x = Station, y = Perc_annual)) +
      geom_linerange(aes(ymin = Perc_annual_lo, ymax = Perc_annual_hi, colour = Trend_color), size = 1) +
      geom_point_interactive(aes(fill = Trend_color, shape = Trend_color, tooltip = Tooltip_txt), 
                             colour = "black", size = 3) +
      # drop = FALSE: unused factor levels are not omitted from the scale
      # na.translate = FALSE: NAs are not shown in plot or leend 
      scale_colour_manual(values = trend_colours, drop = FALSE, na.translate = FALSE) +
      scale_fill_manual(values = trend_colours, drop = FALSE, na.translate = FALSE) +
      scale_shape_manual(values = trend_shapes, drop = FALSE, na.translate = FALSE) +
      geom_hline(yintercept = 0, color = "grey30") +
      geom_label(aes(y = label_coor, 
                     label = Trend_text), fill = "white", color = "blue3", 
                 label.size = 0, size = 3, hjust = 0.5) +
      scale_x_discrete(limits = levels(data_for_plot$Station)) +
      coord_flip(ylim = y_ran[[speciesgroup]][[type]]) +
      labs(title = glue("Trend ({type}-term) {trendtitle_asterisk}"), y = "") +
      theme_bw() 
    
  }
  
}

}


if (FALSE){
  gg_trends_list[[1]][["long"]]
  girafe(ggobj = gg_trends_list[[1]][["long"]], height_svg = 5.7, width_svg = 9)
  gg_trends_list[[1]][["short"]]
  gg_trends_list[[2]][["long"]]
  gg_trends_list[[2]][["short"]]
}


```

```{r, fig.width=10, fig.height=8, warning=FALSE}

# 06_combine_plots

ggcomb_list <- list(NULL, NULL)

# For extra text regarinf unit under plot
# (and in case of Hg, note about 'length-adjusted concentrations')
space_footnote <- 0.15

# if (params$basis_trends == "WWa"){
for (speciesgroup in speciesgroups){
  
  # if (params$include_trend == "TRUE"){
    
    # Top row: 3 plots (tile + two trend plots)
    plotlist_row1 <- list(
      gg_tile_list[[speciesgroup]] + theme(legend.position = "none"), 
      gg_trends_list[[speciesgroup]][[1]] +
        # labs(caption = "") +
        theme(axis.title.y = element_blank(),
              axis.text.y = element_blank(),
              legend.position = "none"), 
      gg_trends_list[[speciesgroup]][[2]] + 
        # labs(caption = "test") +
        theme(axis.title.y = element_blank(),
              axis.text.y = element_blank())
      )
    
    # Bottom row: 2 plots with text only (footnotes, one under the tile plot + one under the trend plots)
    
    trend_footnote <- ifelse(
      params$param %in% "HG" & speciesgroup == 1,
      "* Trends are based on length-adjusted concentrations",
      ""
    )
    
    plotlist_row2 <- list(
      ggplot() + theme_nothing() + draw_label(glue::glue("Unit: {params$conc_unit}"), 
                                              x = 0.99, y = 0.5, hjust = 1, size = 11),
      ggplot() + theme_nothing() + draw_label(trend_footnote, 
                                              x = 0.99, y = 0.5, hjust = 1, size = 11)
      )
    

  ggcomb_list[[speciesgroup]] <- cowplot::plot_grid(
    # Top row plots (actual plots)
    cowplot::plot_grid(
      plotlist = plotlist_row1,
      nrow = 1, ncol = 3,
      rel_widths = c(2.7, 0.75, 1.25)
    ),
    # Bottom row plots (footnotes)
    cowplot::plot_grid(
      plotlist = plotlist_row2,
      nrow = 1, ncol = 2,
      rel_widths = c(2.7, 0.75 + 1.25)
    ),
    ncol = 1, nrow = 2, 
    rel_heights = c(3, space_footnote)
  )
    
  ggcomb_legend <- cowplot::get_legend(gg_tile_list[[speciesgroup]])
  
  # Set name of figure file (mercury in cod+birds is treated as a special case)
  if (params$basis_medians != params$basis_trends & speciesgroup == 1){
    filename <- glue::glue("Figures/431/{params$param}-{params$basis_medians}-{params$basis_trends}_combo_{speciesgroup}.png")
  } else {
    filename <- glue::glue("Figures/431/{params$param}_combo_{speciesgroup}.png")
  }
  
  if (params$include_trend == "TRUE"){
    width <- 14
  } else {
    width <- 14*2.7/(2.7 + 0.75 + 1.25)
  }
  # Save
  # ggsave(filename, ggcomb_list[[speciesgroup]], width = width, height = 8, dpi = 200)
    
  # Make and save legend
  filename <- glue::glue("Figures/431/_combo_legend.png")
  # ggsave(filename, ggdraw(ggcomb_legend), width = 2, height = 4, dpi = 200)
  
}

# ggcomb_list[[1]]
# ggcomb_list[[2]]




```


```{r}

if (!is.null(ggcomb_list[[1]])){
  
  girafe( ggobj = ggcomb_list[[1]], width_svg = 12, height_svg = 6)
  
}

# if (!is.null(ggcomb_list[[1]]) & trendtitle_asterisk == "*"){
#   
#   cat("Trends were based on length-adjusted concentrations")
#   
# }

```


```{r, results='asis'}

  # Showing explanatory text below plot (shown only if trends were based on length-adjusted concentrations)

  if (trendtitle_asterisk == "*" & params$called_from_mother %in% c("TRUE","FALSE")){
    
    # If this is called from e.g. Milkys_2021_metals.Rmd, include 'envir=environment()'  
    if (params$called_from_mother == "TRUE"){
      envir <- environment() 
    } else if (params$called_from_mother == "FALSE"){
      envir <- globalenv() 
    } 
    heading <- knitr::knit_child(
      text = "`*` Trends were based on length-adjusted concentrations",
      envir = envir, quiet=TRUE)
    cat(unlist(heading), sep = "\n")
    cat("\n\n\n")
  }


```



```{r}

if (!is.null(ggcomb_list[[2]])){
  
  girafe( ggobj = ggcomb_list[[2]], width_svg = 12, height_svg = 6)
  
}

```


```{r, results='asis'}

  # Showing explanatory text below plot (shown only if there are suspect trends)

  i <- 2

  if (!is.na(text_trends_manual[[i]]) & params$called_from_mother %in% c("TRUE","FALSE")){
    
    # If this is called from e.g. Milkys_2021_metals.Rmd, include 'envir=environment()'  
    if (params$called_from_mother == "TRUE"){
      envir <- environment() 
    } else if (params$called_from_mother == "FALSE"){
      envir <- globalenv() 
    } 
    heading <- knitr::knit_child(
      text = text_trends_manual[[i]],
      envir = envir, quiet=TRUE)
    cat(unlist(heading), sep = "\n")
    cat("\n\n\n")
  }

```


```{r}
# 05_trend_plot_legend 

# ggdraw(ggcomb_legend)

```


```{r, results='asis'}

#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o
#
## Last year's concentrations           
#
#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o


# 07b_lastyear_heading

# Inserts "Concentrations in the last year" header in document, but only if eqsplot or prorefplot == "TRUE"

if (params$eqsplot %in% c("log", "ordinary", "TRUE") | params$prorefplot == "TRUE"){
  
  # If this is called from e.g. Milkys_2021_metals.Rmd, include 'envir=environment()'  
  if (params$called_from_mother == "TRUE"){
    heading <- knitr::knit_child(
      text = c( 
        '## Concentrations in the last year'),
      envir=environment() , quiet=TRUE)
    cat(unlist(heading), sep = "\n")
    cat("    \n")
  } else if (params$called_from_mother == "FALSE"){
    # If this is just knitted on its own  
    heading <- knitr::knit_child(
      text = c( 
        '## Concentrations in the last year'),
      quiet=TRUE)
    cat(unlist(heading), sep = "\n")
    cat("    \n")
  }
  
}

```


```{r, warning=FALSE, message=FALSE}  

# 06_ratio_data_1

#
# Cod + eider duck raw data
#

# Note: the 'current_year' in get_data_raw means "only series that includes current_year",
#   previous years are also included

if (params$param %in% "HG"){
  fish_tissue <- "Muskel"
} else {
  fish_tissue <- "Lever"
}
df1 <- dat_raw1 <- get_data_raw(params$param, "Gadus morhua", fish_tissue, params$basis_medians, 
                                include_year=current_year, filename_109 = filename_109)  
dat_raw2 <- get_data_raw(params$param, "Somateria mollissima", "Blod", "WW", include_year=current_year)
dat_raw3 <- get_data_raw(params$param, "Somateria mollissima", "Egg", "WW", include_year=current_year)  

dat_raw_codeider <- bind_rows(dat_raw1, dat_raw2, dat_raw3)

#
# Cod + eider duck median data
#
dat_to_add <- dat_raw_codeider %>%
  filter(MYEAR %in% current_year & !is.na(Value)) %>%
  group_by(PARAM, LATIN_NAME, TISSUE_NAME, STATION_CODE, Basis) %>%
  summarise(
    Value_lo = quantile(Value, probs = 0.25),                            # note: 1st and 3rd quartiles for cod + eider
    Value_hi = quantile(Value, probs = 0.75), .groups = "drop") 

dat_last_codeider <- dat_medians_list[[1]] %>%                           # 1 for cod + eider
  filter(MYEAR %in% current_year) %>%
  left_join(dat_to_add, by = c("PARAM", "LATIN_NAME", "TISSUE_NAME", "STATION_CODE", "Basis"))

# For sorting N to S, add
# mutate(Station = forcats::fct_rev(Station))

# Check that station codes are the same
st1 <- unique(dat_to_add$STATION_CODE) %>% sort()
st2 <- unique(dat_medians_list[[1]]$STATION_CODE) %>% sort()
if (!identical(st1,st2)){
  warning("Station codes are not identical")
}


```



```{r, warning=FALSE, message=FALSE}  

# 06_ratio_data_2

#
# Blue mussel raw data
#

# debugonce(get_data_raw)  
dat_raw_mussel <- get_data_raw(params$param, "Mytilus edulis", "Whole soft body", "WW", 
                               current_year, filename_109 = filename_109)  

if (nrow(dat_raw_mussel) > 0){
  
  #
  # Blue mussel median data
  #
  dat_to_add <- dat_raw_mussel %>%
    filter(MYEAR %in% current_year & !is.na(Value)) %>%
    group_by(PARAM, LATIN_NAME, TISSUE_NAME, STATION_CODE, Basis) %>%
    summarise(
      Value_lo = min(Value),                             # note: min and max for blue mussel
      Value_hi = max(Value), .groups = "drop") %>%
    mutate(STATION_CODE = ifelse(STATION_CODE == "36A1", "36A", STATION_CODE))
  
  dat_last_mussel <- dat_medians_list[[2]] %>%                           # 2 for blue mussel
    filter(MYEAR %in% current_year) %>%
    left_join(dat_to_add, by = c("PARAM", "LATIN_NAME", "TISSUE_NAME", "STATION_CODE", "Basis"))
  
  st1 <- unique(dat_to_add$STATION_CODE) %>% sort()
  st2 <- unique(dat_medians_list[[2]]$STATION_CODE) %>% sort()
  if (!identical(st1,st2)){
    warning("Station codes are not identical")
  }
  
}


if (FALSE){
  # Check station names in the two
  setdiff(st1,st2)
  setdiff(st2,st1)
  # dat_medians_list[[2]] %>% filter(STATION_CODE == "28A2") %>% View()
}

```


```{r, warning=FALSE, message=FALSE}

# 06_ratio_data_3

if (nrow(dat_raw_mussel) > 0){
  
  dat_last_list <- list(
    dat_last_codeider,
    dat_last_mussel)
  
  dat_raw_list <- list(
    dat_raw_codeider %>% 
      filter(MYEAR %in% current_year & !is.na(Value)),
    dat_raw_mussel %>% 
      filter(MYEAR %in% current_year & !is.na(Value)) %>% 
      mutate(STATION_CODE = ifelse(STATION_CODE == "36A1", "36A", STATION_CODE))
  )
  
} else {
  
  dat_last_list <- list(
    dat_last_codeider)
  
  dat_raw_list <- list(
    dat_raw_codeider %>% 
      filter(MYEAR %in% current_year & !is.na(Value))
  )
  
  speciesgroups <- 1
  
  
}



for (speciesgroup in speciesgroups){
  
  dat_last_list[[speciesgroup]] <- dat_last_list[[speciesgroup]] %>% 
    ungroup() %>%
    mutate(
      Proref_ratio_lo = Value_lo/Proref,
      Proref_ratio_hi = Value_hi/Proref,
      EQS_ratio_lo = Value_lo/EQS,
      EQS_ratio_hi = Value_hi/EQS,
      Proref_line = Proref/EQS,         # for adding extra line for proref
      Proref_tooltip = paste0(
        "Conc.: ", Value, " (Min-max: ", Value_lo, "-", Value_hi, ")\n",
        "Ratio: ", Proref_ratio, " (Min-max: ", Proref_ratio_lo, "-", Proref_ratio_hi, ")\n"),
      EQS_tooltip = paste0(
        "Conc.: ", Value, " (Min-max: ", Value_lo, "-", Value_hi, ")")
    ) %>%
    left_join(
      dat_trends_plot_list[[speciesgroup]] %>% 
        filter(Trend_type %in% "short") %>%
        select(PARAM, LATIN_NAME, TISSUE_NAME, STATION_CODE, Trend_color),
      by = c("PARAM", "LATIN_NAME", "TISSUE_NAME", "STATION_CODE")
    )
  
  sel <- is.na(dat_last_list[[speciesgroup]]$Trend_color)
  dat_last_list[[speciesgroup]]$Trend_color[sel] <- "No change"
  
  dat_raw_list[[speciesgroup]] <- dat_raw_list[[speciesgroup]] %>% 
    mutate(
      Proref_ratio = Value/Proref,
      EQS_ratio = Value/EQS,
      Proref_tooltip = paste0(
        "Conc.: ", Value, "\n",
        "Ratio: ", round(Proref_ratio, 3)),
      EQS_tooltip = paste0(
        "Conc.: ", Value, "\n",
        "Ratio: ", round(EQS_ratio, 3)),
      FLAG1 = case_when(
        PARAM %in% c('SCCP eksl. LOQ', 'MCCP eksl. LOQ') & Value == 0 ~ "<",
        TRUE ~ FLAG1)
    ) %>%
    # Add Station
    left_join(
      dat_last_list[[speciesgroup]] %>% 
        select(PARAM, LATIN_NAME, TISSUE_NAME, STATION_CODE, Station),
      by = c("PARAM", "LATIN_NAME", "TISSUE_NAME", "STATION_CODE")
    )
    
  
}

# Number of rows in data
# map_int(dat_last_list, nrow)
# map_int(dat_raw_list, nrow)

```

```{r, results='asis'}


#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o
#
### EQS           
#
#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o


# 06b_eqs_heading

# Inserts "EQS" header in document, but only if eqsplot is "log" or "ordinary" (y-scale)

if (params$eqsplot %in% c("log", "ordinary", "TRUE")){
  
  # If this is called from e.g. Milkys_2021_metals.Rmd, include 'envir=environment()'  
  if (params$called_from_mother == "TRUE"){
    heading <- knitr::knit_child(
      text = c( 
        '### EQS ratio', 
        '**Concentration / EQS threshold**'),
      envir=environment() , quiet=TRUE)
  } else {
    # If this is just knitted on its own  
    heading <- knitr::knit_child(
      text = c( 
        '### EQS ratio', 
        '**Concentration / EQS threshold**'),
      quiet=TRUE)
  }
  
  cat(unlist(heading), sep = "\n")
  cat("    \n")
}

```



```{r, fig.width=8, fig.height=5.5, warning=FALSE}

# 07_eqsratio_plot


plot_eqsratio_list <- list(NULL, NULL)

if (params$eqsplot %in% c("log", "ordinary", "TRUE")){
  
  for (speciesgroup in speciesgroups){
    
    data_proref_medians <- dat_last_list[[speciesgroup]]
    data_proref_samples <- dat_raw_list[[speciesgroup]]
    
    # Order stations correctly
    data_proref_medians <- data_proref_medians %>%
      ungroup() %>%
      left_join(lookup_stations %>% select(STATION_CODE, Order), by = "STATION_CODE") %>%
      arrange(Order) %>% # View()
      mutate(Station = forcats::fct_inorder(Station))
    data_proref_samples <- data_proref_samples %>%
      ungroup() %>%
      left_join(lookup_stations %>% select(STATION_CODE, Order), by = "STATION_CODE") %>% # View()
      arrange(Order) %>%
      mutate(Station = forcats::fct_inorder(Station))
    
    # Set plot title (mercury in cod+birds is treated as a special case)
    if (params$param %in% "HG" & speciesgroup == 1 & params$basis_medians == "WW"){
      plot_title <- paste0("EQS ratio, ", dat_medians$Parameter.Name[1], " (not length-adjusted) in ", speciesgroup_txt[[speciesgroup]])
    } else if (params$param %in% "HG" & speciesgroup == 1 & params$basis_medians == "WWa"){
      plot_title <- paste0("EQS ratio, ", dat_medians$Parameter.Name[1], " (length-adjusted) in ", speciesgroup_txt[[speciesgroup]])
    } else {
      plot_title <- paste0("EQS ratio, ", dat_medians$Parameter.Name[1], " in ", speciesgroup_txt[[speciesgroup]])
    }
    
    if (params$include_trend == "TRUE"){
      
      gg <- ggplot(data_proref_medians, 
                   aes(Station, EQS_ratio)) +
        # The next line (median points) needs to be here (even if it is repeated after the sample points) to keep x order correct
        geom_point(aes(fill = Trend_color, shape = Trend_color), colour = "black", size = 3) +
        geom_point_interactive(data = subset(data_proref_samples, is.na(FLAG1)), 
                               aes(tooltip = EQS_tooltip), color = "grey50", shape = 1, size = 2) +
        geom_point_interactive(data = subset(data_proref_samples, !is.na(FLAG1)), 
                               aes(tooltip = EQS_tooltip), color = "grey50", shape = 6, size = 2) +
        geom_linerange(aes(ymin = EQS_ratio_lo, ymax = EQS_ratio_hi, colour = Trend_color), size = 1) +
        geom_point(aes(fill = Trend_color, shape = Trend_color), colour = "black", size = 3) +
        scale_colour_manual("Time trend", values = trend_colours, drop = FALSE) +
        scale_fill_manual("Time trend", values = trend_colours, drop = FALSE) +
        scale_shape_manual("Time trend", values = trend_shapes, drop = FALSE) +
        geom_hline(yintercept = 1, color = "red2", linetype = "dashed") +
        annotate("text", x = -1.7, y = 1, label = "EQS", color = "red2", hjust = 0, vjust = -0.3) +
        coord_cartesian(xlim = c(-1.5, length(data_proref_medians$Station))) +
        labs(title = plot_title, 
             y = "Concentration/EQS") +
        theme_bw() +
        ggeasy::easy_rotate_x_labels(angle = -45)
      
    } else {
      
      gg <- ggplot(data_proref_medians, 
                   aes(Station, EQS_ratio)) +
        # The next line (median points) needs to be here (even if it is repeated after the sample points) to keep x order correct
        geom_point(colour = "black", size = 3) +
        geom_point_interactive(data = subset(data_proref_samples, is.na(FLAG1)), 
                               aes(tooltip = EQS_tooltip), color = "grey50", shape = 1, size = 2) +
        geom_point_interactive(data = subset(data_proref_samples, !is.na(FLAG1)), 
                               aes(tooltip = EQS_tooltip), color = "grey50", shape = 6, size = 2) +
        geom_linerange(aes(ymin = EQS_ratio_lo, ymax = EQS_ratio_hi), size = 1) +
        geom_point(colour = "black", size = 3) +
        geom_hline(yintercept = 1, color = "red2", linetype = "dashed") +
        annotate("text", x = -1.7, y = 1, label = "EQS", color = "red2", hjust = 0, vjust = -0.3) +
        coord_cartesian(xlim = c(-1.5, length(data_proref_medians$Station))) +
        labs(title = plot_title, 
             y = "Concentration/EQS") +
        theme_bw() +
        theme(legend.title = element_blank()) +
        ggeasy::easy_rotate_x_labels(angle = -45) +
        theme(plot.margin = margin(12, 60, 4, 24))      # need extra right margin because there is no legend 
      
    }
    
    
    # Add proref line on EQS plot
    
    if (!params$param %in% c("SCCP eksl. LOQ", "MCCP eksl. LOQ")){
    
    proref <- data_proref_medians$Proref_line
    proref <- proref[!is.na(proref)][1]   # the first non-negative value
    gg <- gg +
      geom_hline(yintercept = proref, color = "blue2", linetype = "dashed") +
      annotate("text", x = -1.7, y = proref, label = "PROREF", color = "blue2", hjust = 0, vjust = -0.3)
    
    }
    
    # Set name of figure file (mercury in cod+birds is treated as a special case)
    if (params$basis_medians != params$basis_trends & speciesgroup == 1){
      filename <- glue::glue("Figures/431/{params$param}-{params$basis_medians}-{params$basis_trend}_eqsratio_ord_{speciesgroup}.png")
    } else {
      filename <- glue::glue("Figures/431/{params$param}_eqsratio_ord_{speciesgroup}.png")
    }
    
    # Save
    # ggsave(filename, gg, 
    #       width = 9, height = 6, dpi = 200)
    
    # Save again, but this time on log scale  
    filename <- sub("eqsratio_ord", "eqsratio_log", filename, fixed = TRUE)
    
    if (!params$param %in% c("SCCP eksl. LOQ", "MCCP eksl. LOQ")){
      gg2 <- gg + scale_y_log10()
    } else {
      tr <- scales::trans_new("", transform = function(x) log(x + 0.001), inverse = function(x) exp(x)- 0.001)
      gg2 <- gg + 
        scale_y_continuous(trans = tr, 
                           breaks = c(0, 0.001, 0.01, 0.1, 1),
                           labels = function(lab) round(lab, 3)
        )
    }
    
    # ggsave(filename, gg2, width = 9, height = 6, dpi = 200)
      
    
    if (params$eqsplot %in% c("ordinary", "TRUE")){
      plot_eqsratio_list[[speciesgroup]] <- gg
    } else if (params$eqsplot %in% "log"){
      plot_eqsratio_list[[speciesgroup]] <- gg2
    }
    
  }
  

}

```

```{r}

if (params$eqsplot %in% c("log", "ordinary", "TRUE")){
  if (!is.null(plot_eqsratio_list[[1]])){
    
    girafe(ggobj = plot_eqsratio_list[[1]], width_svg = 10, height_svg = 6)
    
  }
}

```

```{r}

if (params$eqsplot %in% c("log", "ordinary", "TRUE")){
  if (!is.null(plot_eqsratio_list[[2]])){
    
    girafe(ggobj = plot_eqsratio_list[[2]], width_svg = 10, height_svg = 6)
    
  }
}

```



```{r, results='asis'}

#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o
#
### PROREF           
#
#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o

# 07b_proref_heading

# Inserts "Proref" header in document, but only if prorefplot == "TRUE"

if (params$prorefplot == "TRUE"){
  
  # If this is called from e.g. Milkys_2021_metals.Rmd, include 'envir=environment()'  
  if (params$called_from_mother == "TRUE"){
    heading <- knitr::knit_child(
      text = c( 
        '### PROREF ratio', 
        '**Concentration / PROREF threshold**'),
      envir=environment() , quiet=TRUE)
    cat(unlist(heading), sep = "\n")
    cat("    \n")
  } else if (params$called_from_mother == "TRUE"){
    # If this is just knitted on its own  
    heading <- knitr::knit_child(
      text = c( 
        '### PROREF ratio', 
        '**Concentration / PROREF threshold**'),
      quiet=TRUE)
    cat(unlist(heading), sep = "\n")
    cat("    \n")
  }
  
}

```



```{r, fig.width=8, fig.height=5.5, warning=FALSE}

# 08_prorefratio_plot

plot_prorefratio_list <- list(NULL, NULL)

if (params$prorefplot == "TRUE"){
  
  for (speciesgroup in speciesgroups){
    
    data_proref_medians <- dat_last_list[[speciesgroup]]
    data_proref_samples <- dat_raw_list[[speciesgroup]]
    
    #  mutate(
    #    STATION_CODE = ifelse(STATION_CODE == "36A", "36A1", STATION_CODE)
    #  )
    
    if (speciesgroup == 1){
      # No Proref for the bird stations, so we delete them
      data_proref_medians <- data_proref_medians %>%
        filter(!Station %in% c("19N Kongsfjorden (eider duck blood)", "19N Kongsfjorden (eider duck egg)")) %>%
        mutate(Station = forcats::fct_drop(Station))
      data_proref_samples <- data_proref_samples %>%
        filter(!Station %in% c("19N Kongsfjorden (eider duck blood)", "19N Kongsfjorden (eider duck egg)")) %>%
        mutate(Station = factor(Station, levels = levels(data_proref_medians$Station)))
    }
    
    # Order stations correctly
    data_proref_medians <- data_proref_medians %>%
      ungroup() %>%
      left_join(lookup_stations %>% select(STATION_CODE, Order), by = "STATION_CODE") %>%
      arrange(Order) %>%
      mutate(Station = forcats::fct_inorder(Station))
    data_proref_samples <- data_proref_samples %>%
      # mutate( STATION_CODE = ifelse(STATION_CODE == "36A1", "36A", STATION_CODE)) %>%
      ungroup() %>%
      left_join(lookup_stations %>% select(STATION_CODE, Order), by = "STATION_CODE") %>% # View()
      arrange(Order) %>%
      mutate(Station = forcats::fct_inorder(Station))
    data_proref_samples_overLOQ <- data_proref_samples %>%
      filter(is.na(FLAG1))
    data_proref_samples_underLOQ <- data_proref_samples %>%
      filter(FLAG1 %in% "<")
    
    # Set plot title (mercury in cod+birds is treated as a special case)
    if (params$param %in% "HG" & speciesgroup == 1 & params$basis_medians == "WW"){
      plot_title <- paste0("Proref ratio, ", dat_medians$Parameter.Name[1], " (not length-adjusted) in ", speciesgroup_txt_proref[[speciesgroup]])
    } else if (params$param %in% "HG" & speciesgroup == 1 & params$basis_medians == "WWa"){
      plot_title <- paste0("Proref ratio, ", dat_medians$Parameter.Name[1], " (length-adjusted) in ", speciesgroup_txt_proref[[speciesgroup]])
    } else {
      plot_title <- paste0("Proref ratio, ", dat_medians$Parameter.Name[1], " in ", speciesgroup_txt_proref[[speciesgroup]])
    }
    
    gg <- ggplot(data_proref_medians, 
                 aes(Station, Proref_ratio)) +
      # The next line (median points) needs to be here (even if it is repeated after the sample points) to keep x order correct
      geom_point(aes(fill = Trend_color, shape = Trend_color), colour = "black", size = 3) +
      geom_point_interactive(data = data_proref_samples_overLOQ , 
                             aes(tooltip = Proref_tooltip), color = "grey50", shape = 1, size = 2) +
      geom_point_interactive(data = data_proref_samples_underLOQ , 
                             aes(tooltip = Proref_tooltip), color = "grey50", shape = 6, size = 2) +
      geom_linerange(aes(ymin = Proref_ratio_lo, ymax = Proref_ratio_hi, colour = Trend_color), size = 1) +
      geom_point(aes(fill = Trend_color, shape = Trend_color), colour = "black", size = 3) +
      scale_colour_manual(values = trend_colours, drop = FALSE) +
      scale_fill_manual(values = trend_colours, drop = FALSE) +
      scale_shape_manual(values = trend_shapes, drop = FALSE) +
      geom_hline(yintercept = 1, color = "blue2", linetype = "dashed") +
      annotate("text", x = -1.7, y = 1, label = "PROREF", color = "blue2", hjust = 0, vjust = -0.3) +
      coord_cartesian(xlim = c(-1.5, length(data_proref_medians$Station))) +
      labs(title = plot_title,  
           y = "Concentration/PROREF") +
      theme_bw() +
      theme(legend.title = element_blank()) +
      ggeasy::easy_rotate_x_labels(angle = -45) 
    
    plot_prorefratio_list[[speciesgroup]] <- gg
    
    # Set name of figure file (mercury in cod+birds is treated as a special case)
    if (params$basis_medians != params$basis_trends & speciesgroup == 1){
      filename <- glue::glue("Figures/431/{params$param}-{params$basis_medians}-{params$basis_trends}_prorefratio_ord_{speciesgroup}.png")
    } else {
      filename <- glue::glue("Figures/431/{params$param}_prorefratio_ord_{speciesgroup}.png")
    }
    
    # Save  
    # ggsave(filename, gg, 
    #       width = 9, height = 6, dpi = 200)
    
    # Save again, but this time on log scale  
    filename <- sub("prorefratio_ord", "prorefratio_log", filename, fixed = TRUE)
    # ggsave(filename, gg + scale_y_log10(), 
    #       width = 9, height = 6, dpi = 200)
    
    
  }
  
}


```

```{r}

if (!is.null(plot_prorefratio_list[[1]])){
  
  girafe(ggobj = plot_prorefratio_list[[1]], width_svg = 10, height_svg = 6)
  
}

```

```{r}

if (!is.null(plot_prorefratio_list[[2]])){
  
  girafe(ggobj = plot_prorefratio_list[[2]], width_svg = 10, height_svg = 6)
  
}

```


