---
title: "Fact sheet - metals"
author: "DHJ"
date: "2022-11-01"
output: 
  html_document:
    toc: true
    toc_float: true
---


```{r}

lookup_eqs <- subset(
  read.csv("Input_data/Lookup_tables/Lookup_EQS_limits.csv"),
  Basis == "WW")

```


```{r, echo=FALSE, results='asis', warning=FALSE, message=FALSE}

# References:
# https://bookdown.org/yihui/rmarkdown-cookbook/child-document.html#child-document
# and
# https://stackoverflow.com/a/69392658/1734247 

# Works for a single value of param (one round in the loop)  
# param_values <- c("HG")

# Fails for >= 2 parameters: 
param_values <- c("HG", "CD")

# It works for the first value of param, but on the second round in the loop we get an error when we reach 
# the first chunk ('01_settings'), because knitr has seen the '01_settings' label before (namely on the first round)

# Need to use knit_expand, see here:
# https://cran.r-project.org/web/packages/workflowr/vignettes/wflow-07-common-code.html#share-templates-with-knit_expand

for (param in param_values){
  
  if (param == "HG"){
    basis_medians <- "WWa"
  } else {
    basis_medians <- "WW"
  }
  
  eqsplot <- as.character(param %in% lookup_eqs$PARAM)

  params <- list(
    param = param,
    basis_medians = basis_medians,
    basis_trends = "WW",
    eqsplot = eqsplot,
    include_trend = "TRUE"
  )
  
  res <- knitr::knit_child('434_Report_parameter_interactive_nochunklabels.Rmd', quiet = TRUE)
  cat(res, sep = '\n')
  
}

# Alternative:
# ```{r call_child, child = '434_Report_parameter_interactive.Rmd'}
# ```

```

