---
title: "Report for parameter (431)"
author: "DHJ"
date: "04.10.2022"
params:
  param: "DDEPP"
  basis_medians: "WW"
  basis_trends: "WW"
  include_trend: "TRUE"
  serieslastuntil: 2020
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r, include=FALSE}

#
# NOTE: This file is run by knitting one of the .Rmd files in '434_paramgroups'
#

dat_groups <- read.csv("Input_data/Lookup_tables/Lookup table - substance groups.csv")  
header_param <- subset(dat_groups, PARAM %in% params$param, select = Parameter.Name)[1,1]

```


# `r header_param`  
   
```{r, include=FALSE}

# 01_settings

current_year <- 2021
knitr::opts_chunk$set(echo = FALSE, results = 'hold', warning = FALSE)

```

<style type="text/css">
div.main-container {
  max-width: 1800px;
  margin-left: auto;
  margin-right: auto;
}
</style>


```{r}

library(ggiraph)
# cat("stuff \n")

```

```{r, include=FALSE, cache=TRUE}

# 02_packages

# library(tidyr)
library(ggplot2)
library(lubridate)
library(flextable)
# library(glue)
library(readxl)
library(purrr)
library(glue)
# library(leftcensored)   # DHJ's package (https://github.com/DagHjermann/leftcensored)
library(scico)            # colour palettes incl. "Vik" (https://github.com/thomasp85/scico)

library(cowplot)

# library(safejoin) # https://github.com/moodymudskipper/safejoin

source("431_Report_parameter_functions.R")
source("002_Utility_functions.R")

```


```{r, warning=FALSE, message=FALSE}

# 03_medians_data1

library(dplyr)    # need to load dplyr AFTER ggiraph fro some reason, otherwise error "%>% is not found" 

#
# Get data 
#


# debugonce(get_data_medians)
dat_temporary <- list(
  get_data_medians(param = params$param, 
                   species = "Gadus morhua",
                   tissue = ifelse(params$param %in% "HG", "Muskel", "Lever"),
                   basis = params$basis_medians, 
                   include_year = params$serieslastuntil),
  get_data_medians(param = params$param, 
                   species = "Somateria mollissima",
                   tissue = "Blod",
                   basis = "WW", 
                   include_year = params$serieslastuntil),
  get_data_medians(param = params$param, 
                   species = "Somateria mollissima",
                   tissue = "Egg",
                   basis = "WW", 
                   include_year = params$serieslastuntil),
  get_data_medians(param = params$param, 
                   species = "Mytilus edulis",
                   tissue = "Whole soft body",
                   basis = "WW", 
                   include_year = params$serieslastuntil)
)


# levels(dat_temporary[[1]]$Station)
# levels(dat_temporary[[2]]$Station) 

#
# Stations - for corrrect ordering
#
lookup_stations <- read.csv("Input_data/Lookup_tables/Lookup_stationorder.csv") # %>%


```

```{r}

# 03_medians_data2

library(purrr)
library(ggplot2)
library(glue)
library(cowplot)

#
# Combine cod and eider duck as one group  
#

eider_blood <- "19N Kongsfjorden (eider duck blood)"
eider_egg <- "19N Kongsfjorden (eider duck egg)"

#
# Make 'dat_medians_list'  
#

dat_medians_list <- list()

# List element 1: cod and eider duck

if (nrow(dat_temporary[[2]]) > 0){
  dat_medians_list[[1]] <- bind_rows(
    dat_temporary[[1]],
    dat_temporary[[2]] %>% mutate(Station = eider_blood),
    dat_temporary[[3]] %>% mutate(Station = eider_egg)
  )
} else {
  dat_medians_list[[1]] <- dat_temporary[[1]]
}

dat_medians_list[[1]]$Station <- factor(dat_medians_list[[1]]$Station, 
                                        levels = c(levels(dat_temporary[[1]]$Station), eider_blood, eider_egg))

# For Hg: add an asterisk after station names for stations that are NOT length-adjusted (for Hg only)
# - these data are also used for 'ratio plots' (last year's concentrations)  
if (params$param %in% "HG" & params$basis_medians %in% "WWa"){
  # View(dat_medians_list[[1]])
  tab <- xtabs(~Basis + Station, dat_medians_list[[1]])
  not_length_adjusted <- colnames(tab)[tab[2,] == 0]
  sel <- levels(dat_medians_list[[1]]$Station) %in% not_length_adjusted
  levels(dat_medians_list[[1]]$Station)[sel] <- paste(levels(dat_medians_list[[1]]$Station)[sel], "*")
}


# levels(dat_medians_list[[1]]$Station)

# List element 2 = blue mussel

dat_medians_list[[2]] <- dat_temporary[[4]]

# Check number of rows for cod/birds and blue mussel:
# map(dat_medians_list, nrow)

```


```{r, fig.width=10, fig.height=8, warning=FALSE}

# 04_medians_plot

proref_cols <- c(RColorBrewer::brewer.pal(6, "Blues")[5:2],
                 RColorBrewer::brewer.pal(6, "YlOrRd")[1:5])

col_func <- function(x){cols[x]}

startyr <- 2012

# Trick to avoid red frames also in legend:
# - put 'fill = Proref_ratio_cut' in aes of the first geom_tile (not in the aes of ggplot)
# - set 'alpha = 0' so there is no fill in the EQS tiles 

gg_tile_list <- list()

speciesgroup_txt <- c("cod and eider duck", "blue mussel")
speciesgroup_txt_proref <- c("cod", "blue mussel")

for (speciesgroup in 1:2){
  
  if (nrow(dat_medians_list[[speciesgroup]]) > 0){
    
    dat_medians <- dat_medians_list[[speciesgroup]] %>%
      mutate(
        Value_txt = case_when(
          is.na(FLAG1) ~ signif2(Value, 2, maxdigits = 5),
          !is.na(FLAG1) & Value > 0 ~ paste0("<", signif2(Value, 2, maxdigits = 4)),
          !is.na(FLAG1) & Value == 0 ~ "0"                                # for 'SCCP eksl. LOQ' + 'MCCP eksl. LOQ'
          ),
        txt_conc = paste0("Median value: ", Value_txt, 
                                   " (", signif(Value_min, 2), "-", signif(Value_max, 2), "; N =", N_median, ")"),
        txt_perc = paste0("25% and 75% percentiles: ", signif(Value_p25, 2), "-", signif(Value_p75, 2)),
        txt_loq = paste0("Measurements over LOQ: ", Over_LOQ, 
                                   " (", signif(100*(Over_LOQ/N_median), 1), " %); median LOQ = ", Det_limit),
        txt_eqs = paste0("The median is ", signif(EQS_ratio, 2), " times the EQS (", EQS, ")"),
        txt_proref = paste0("The median is ", signif(Proref_ratio, 2), " times the PROREF (", Proref, ")"),
        Tooltip_txt = txt_conc,
        Tooltip_txt = ifelse(N_median > 5, paste(Tooltip_txt, "<br>", txt_perc), Tooltip_txt),
        Tooltip_txt = ifelse(Over_LOQ < N_median, paste(Tooltip_txt, "<br>", txt_loq), Tooltip_txt),
        Tooltip_txt = ifelse(!is.na(EQS), paste(Tooltip_txt, "<br>", txt_eqs), Tooltip_txt),
        Tooltip_txt = ifelse(!is.na(Proref), paste(Tooltip_txt, "<br>", txt_proref), Tooltip_txt)
        )

    

    # Set plot title (mercury in cod+birds is treated as a special case)
    if (params$param %in% "HG" & speciesgroup == 1 & params$basis_medians == "WW"){
      plot_title <- paste0(dat_medians$Parameter.Name[1], " (not length-adjusted) in ", speciesgroup_txt[[speciesgroup]])
    } else if (params$param %in% "HG" & speciesgroup == 1 & params$basis_medians == "WWa"){
      plot_title <- paste0(dat_medians$Parameter.Name[1], " (length-adjusted) in ", speciesgroup_txt[[speciesgroup]])
    } else {
      plot_title <- paste0(dat_medians$Parameter.Name[1], " in ", speciesgroup_txt[[speciesgroup]])
    }
    
    gg_tile_list[[speciesgroup]] <- ggplot(dat_medians, aes(MYEAR, Station)) +
      geom_tile(aes(fill = Proref_ratio_cut)) + 
      geom_tile(data = subset(dat_medians, Above_EQS %in% "Over"),
                color = "red", size = 1, height = 0.9, width = 0.9, alpha = 0) +
      geom_text_interactive(aes(label = Value_txt, tooltip = Tooltip_txt), nudge_y = 0, size = 3) +
      # geom_text(aes(label = LOQ_label), size = 3, nudge_y = 0.3) +
      scale_fill_manual("Proref ratio", values = proref_cols, na.value = "grey85") +
      scale_color_manual(values = c("red", "white")) +
      scale_alpha_manual(values = c(1, 0)) +
      scale_x_continuous(breaks = seq(startyr, 2020, 2), 
                         limits = c(startyr-0.5, current_year+0.5)) +
      theme_bw() +
      guides(colour = "none") +
      labs(
        title = plot_title,
        x = "Year", y = "")
    
  } else {
    
    gg_tile_list[[speciesgroup]] <- NULL
    
  }
  
}

if (FALSE){
  gg_tile_list[[1]]
  gg_tile_list[[2]]
  girafe(ggobj = gg_tile_list[[1]], height_svg = 5.7, width_svg = 9)
  
  # Special case: SCCP and MCCP (eksl. LOQ)
  width_tileplot_only <- 2.7 / (2.7 + 0.75 + 1.25)
  for (speciesgroup in 1:2){
    filename <- glue::glue("Figures/431/{params$param}_combo_{speciesgroup}.png")
    # ggsave(filename, gg_tile_list[[speciesgroup]], width = 14*width_tileplot_only, height = 8, dpi = 200)
  }
  
}

```

```{r}

# 05_trends_settings

shape_order <- c("Increasing", "Decreasing", "No change")
colour_order <- shape_order
  
trend_shapes <- c(24, 25, 21) %>% setNames(shape_order)
trend_colours <- c("red3", "green4", "grey20") %>% setNames(colour_order)
trend_fill <- c("red2", "green2", "grey20") %>% setNames(colour_order)

```

```{r}

# 05_trends_data

dat_trends_plot_list <- purrr::map(
  dat_medians_list, 
  get_data_trends, basis = params$basis_trends, include_year = current_year
)

# debugonce(get_data_trends)
# chck <- get_data_trends(dat_medians_list[[1]],  basis = "WWa", include_year = current_year)
# chck <- get_data_trends(dat_medians_list[[2]],  include_year = current_year)

# table(addNA(dat_trends_plot_list[[1]]$Station))
# levels(dat_trends_plot_list[[1]]$Station)
# View(dat_trends_plot_list[[1]])

# Check number of rows for cod/birds and blue mussel:
# map(dat_trends_plot_list, nrow)

```

```{r}

# 05_trends_create_plots

# Which species groups do we have? 
if (is.null(dat_trends_plot_list[[1]])){
  speciesgroups <- 2 
} else if (is.null(dat_trends_plot_list[[2]])){
  speciesgroups <- 1 
} else {
  speciesgroups <- 1:2
}

if (params$include_trend == "TRUE"){

#
# Two things happens here: 
# 1) Store y range in a list (used to set limits), and 
# 2) add label coordinate (label_coor) to the data 
# - needed because the label coordinate is inside aes()  
# - when we didn't do this, the label of plot no. 1 was ok after making plot.no. 1, but
#   moved as we made plots no. 2,3,4.... :-o
#

y_ran <- list(list(), list())

for (speciesgroup in speciesgroups){
  
  dat_trends_plot_list[[speciesgroup]] <- dat_trends_plot_list[[speciesgroup]] %>%
    mutate(
      Tooltip_txt = paste0(
        ifelse(Trend_type == "short", "10-year trend: ", "Long-term trend: "), Trend_string),
      Tooltip_txt = ifelse(
        Trend_string %in% c("Decreasing", "Increasing"),
        paste0(Tooltip_txt, "<br>Change per year: ", sprintf("%.1f", Perc_annual), 
              "% (conf.int.: ", round(Perc_annual_hi,1), " - ", round(Perc_annual_lo,1), ")"),
        Trend_string
        )
    )

  dat_trends_plot_list[[speciesgroup]]$label_coor <- NA

  for (type in c("long", "short")){
    
    # y range equals the point estimates 
    y_ran[[speciesgroup]][[type]] <- dat_trends_plot_list[[speciesgroup]] %>% 
      filter(Trend_type %in% type) %>% 
      pull(Perc_annual) %>%
      range(na.rm = TRUE)
    y_ran[[speciesgroup]][[type]] <- range(y_ran[[speciesgroup]][[type]], 0)
    
  sel <- dat_trends_plot_list[[speciesgroup]]$Trend_type %in% type
  dat_trends_plot_list[[speciesgroup]]$label_coor[sel] <- mean(y_ran[[speciesgroup]][[type]])

  }
}


gg_trends_list <- list(list(), list())

for (speciesgroup in speciesgroups){

  for (type in c("long", "short")){
    
    tab <- table(dat_medians_list[[speciesgroup]]$Station)
    station_levels <- names(tab)
    station_levels <- station_levels[tab != 0]
    data_for_plot <- dat_trends_plot_list[[speciesgroup]] %>% 
      filter(Trend_type %in% type) %>%
      mutate(Station = factor(Station, levels = station_levels))
    gg_trends_list[[speciesgroup]][[type]] <- ggplot(
      data_for_plot, aes(x = Station, y = Perc_annual)) +
      geom_linerange(aes(ymin = Perc_annual_lo, ymax = Perc_annual_hi, colour = Trend_color), size = 1) +
      geom_point_interactive(aes(fill = Trend_color, shape = Trend_color, tooltip = Tooltip_txt), 
                             colour = "black", size = 3) +
      scale_colour_manual(values = trend_colours, drop = FALSE) +
      scale_fill_manual(values = trend_colours, drop = FALSE) +
      scale_shape_manual(values = trend_shapes, drop = FALSE) +
      geom_hline(yintercept = 0, color = "grey30") +
      geom_label(aes(y = label_coor, 
                     label = Trend_text), fill = "white", color = "blue3", 
                 label.size = 0, size = 3, hjust = 0.5) +
      scale_x_discrete(limits = levels(data_for_plot$Station)) +
      coord_flip(ylim = y_ran[[speciesgroup]][[type]]) +
      labs(title = glue("Trend ({type}-term)"), y = "") +
      theme_bw() 
    
  }
  
}

}


if (FALSE){
  gg_trends_list[[1]][["long"]]
  girafe(ggobj = gg_trends_list[[1]][["long"]], height_svg = 5.7, width_svg = 9)
  gg_trends_list[[1]][["short"]]
  gg_trends_list[[2]][["long"]]
  gg_trends_list[[2]][["short"]]
}


```

```{r, fig.width=10, fig.height=8, warning=FALSE}

# 06_combine_plots

ggcomb_list <- list()

for (speciesgroup in speciesgroups){
  
  if (params$include_trend == "TRUE"){

  ggcomb_list[[speciesgroup]] <- cowplot::plot_grid(
    gg_tile_list[[speciesgroup]] + theme(legend.position = "none"), 
    gg_trends_list[[speciesgroup]][[1]] + 
      theme(axis.title.y = element_blank(),
            axis.text.y = element_blank(),
            legend.position = "none"), 
    gg_trends_list[[speciesgroup]][[2]] + 
      theme(axis.title.y = element_blank(),
            axis.text.y = element_blank()), 
    nrow = 1, ncol = 3,
    rel_heights = 3,
    rel_widths = c(2.7, 0.75, 1.25)
  )
  
  } else {
    
    ggcomb_list[[speciesgroup]] <- gg_tile_list[[speciesgroup]] + 
      theme(legend.position = "none")
    
  }
  
  ggcomb_legend <- cowplot::get_legend(gg_tile_list[[speciesgroup]])
  
  # Set name of figure file (mercury in cod+birds is treated as a special case)
  if (params$basis_medians != params$basis_trends & speciesgroup == 1){
    filename <- glue::glue("Figures/431/{params$param}-{params$basis_medians}-{params$basis_trends}_combo_{speciesgroup}.png")
  } else {
    filename <- glue::glue("Figures/431/{params$param}_combo_{speciesgroup}.png")
  }
  
  if (params$include_trend == "TRUE"){
    width <- 14
  } else {
    width <- 14*2.7/(2.7 + 0.75 + 1.25)
  }
  # Save
  # ggsave(filename, ggcomb_list[[speciesgroup]], width = width, height = 8, dpi = 200)
    
  # Make and save legend
  filename <- glue::glue("Figures/431/_combo_legend.png")
  # ggsave(filename, ggdraw(ggcomb_legend), width = 2, height = 4, dpi = 200)
  
}

# ggcomb_list[[1]]
# ggcomb_list[[2]]


```


```{r}

if (!is.null(ggcomb_list[[1]])){
  
  girafe( ggobj = ggcomb_list[[1]], width_svg = 12, height_svg = 6)
  
}

```


```{r}

if (!is.null(ggcomb_list[[2]])){
  
  girafe( ggobj = ggcomb_list[[2]], width_svg = 12, height_svg = 6)
  
}

```



