---
title: "911_Check_data_flow_tins"
output: 
  html_document:
    keep_md: true
    toc: true
    toc_float: true
    
---

## 1. Libraries
```{r setup, include=FALSE}  

library(dplyr)
library(ggplot2)
library(readxl)
library(lubridate)
source("100_Download_Aquamonitor_data_R_functions.R")
source("002_Utility_functions.R")

```

## 2. Station  
```{r}
station <- "71G"
```


## 3. Script 101  
```{r}

#
# 1. Legacy data going into script 101
#
data101_through_2018 <- readRDS("Input_data/Data_through_2018.rds") 

#
# 2. New (2019) data going into script 101
#
filename <- list_files("Data_Nivabasen", pattern = "Data_CEMP_Biota")[1]

data101_new <- AqMexport_read_chemistry_table(filename) %>%
  mutate(
    Month = month(CatchDateFirst),
    MYEAR = case_when(
      Month <= 2 ~ year(CatchDateFirst)-1,   # measurments in Jan-Feb belong to the year before
      Month >= 3 ~ year(CatchDateFirst))
  ) %>%
  filter(MYEAR %in% 2019:2020)

if (FALSE){
  xtabs(~MYEAR + PARAM, data101_through_2018 %>% filter(STATION_CODE == station))
}

#
# 3. result of script 101
#
filename <- list_files("Data", pattern = "101_data_updated")[1]
data101_final <- readRDS(paste0("Data/", filename))



```

### 3a. Data read using script 100   
```{r}

data101_new %>% 
  filter(StationCode == station) %>%
  xtabs(~TissueName + MYEAR, .)

```

### 3b. Legacy data   
```{r}

data101_through_2018 %>% 
  filter(STATION_CODE == station) %>%
  xtabs(~TISSUE_NAME + MYEAR, .)

if (FALSE){
  data101_through_2018 %>% 
  filter(STATION_CODE == station) %>%
  ggplot(aes(MYEAR, PARAM)) +
  stat_bin2d(binwidth = 1)
}

```

### 3c. Legacy data 2  
```{r}

data101_through_2018 %>% 
  filter(STATION_CODE == station & MYEAR %in% 2005:2009) %>%
  xtabs(~TISSUE_NAME + PARAM, .)

data101_through_2018 %>% 
  filter(STATION_CODE == station & MYEAR %in% 2017:2019) %>%
  xtabs(~TISSUE_NAME + PARAM, .)

```

### 3d. Final data from script 101
```{r}

data101_final %>% 
  filter(STATION_CODE == station) %>%
  xtabs(~TISSUE_NAME + MYEAR, .)

```

### 3d. Final data from script 101 (2)
```{r}

data101_final %>% 
  filter(STATION_CODE == station & PARAM %in% c("VDSI","Intersex")) %>%
  xtabs(~PARAM + MYEAR, .)  

```

## 4. Script 109
```{r}

filename <- list_files("Data", pattern = "109_adjusted_data")[1]
data109_final <- readRDS(paste0("Data/", filename))

data109_final %>% 
  filter(STATION_CODE == station & PARAM %in% c("VDSI","Intersex")) %>%
  xtabs(~PARAM + MYEAR, .) 

```

## 5. Script 110
```{r}

filename <- list_files("Data", pattern = "110_mediandata_updated")[1]
data110_final <- readRDS(paste0("Data/", filename))

data110_final %>% 
  filter(STATION_CODE == station & PARAM %in% c("VDSI","Intersex")) %>%
  xtabs(~PARAM + MYEAR, .) 

```

## 5. Script 201
```{r}

filename <- list_files("Big_excel_table", pattern = "Data_xl_.+.rds")[1]
data201_final <- readRDS(paste0("Big_excel_table/", filename))

data201_final %>% 
  filter(STATION_CODE == station) %>%
  select(PARAM, Substance.Group, LATIN_NAME, TISSUE_NAME, STATION_CODE, Basis, 
         Yr_2003, Yr_2010, Yr_2014, Yr_2018, Yr_2019, N_string, SD_last, EQS)

```
