---
title: "Fact sheet - Chlorinated paraffins (SCCP and MCCP)"
author: "DHJ"
date: "2022-11-01"
output: 
  html_document:
    toc: true
    toc_float: true

---

```{r, include=FALSE}

# 01_settings

current_year <- 2021
knitr::opts_chunk$set(echo = FALSE, results = 'hold', warning = FALSE)

width_svg <- 12
height_svg <- 4.5

# Set to TRUE for testing whether trends are in correct order  
# - setting to TRUE will add the station names on top of the trend bars/labels
trends_add_station <- FALSE

```

<style type="text/css">
div.main-container {
  max-width: 1800px;
  margin-left: auto;
  margin-right: auto;
}
</style>

```{r, include = FALSE}

#
# Improved version of fact sheet "combo" plots  
# - possible to make adjustments after getting the data for all parameters:
#     - may manipulate station order and station name (e.g. add asterisk) - will apply to all parameters
# - possible to make adjustments after getting the parameter-specific data
#

# selstations <- list (...one or several data sets, e.g, 1. cod + eider duck and 2. blue mussel, or 1. all snails)
# dat_medians_selstations <- map(selstations, get_medians_stations) 
# 
# for each parameter:
#   
# lookup_ref_value - can be EQS, PROREF, BAC or whatever (one table for all species)
# ref_list <- list(ref_type1,2 and ref_basis1,2)  - global variable
# dat_medians_param <-  map(param, get_medians_param, data = dat_medians_selstations, param, ref_list, ) 
# - adds reference values
# - adds Ref_value -> Ratio, Tooltip etc


```

```{r, include = FALSE}

# pick-data-parametergroup

# Parameters to select  
params <- c("SCCP eksl. LOQ", "MCCP eksl. LOQ")
tissues <- c("Lever", "Whole soft body", "Blod", "Egg")

library(dplyr)
library(ggplot2)
library(ggiraph)
library(forcats)
library(glue)
library(tidyr)

source("../002_Utility_functions.R")
source("../431_Report_parameter_functions.R")

knitr::opts_chunk$set(echo = FALSE, results = 'hold', warning = FALSE)

#
# Data 
#

# dat_raw <- readRDS("../Data/109_adjusted_data_2022-09-23.rds")  
dat_medians <- readRDS("../Data/110_mediandata_updated_2022-09-23.rds") 

lookup_stations <- read.csv("../Input_data/Lookup_tables/Lookup_stationorder.csv")  

# HARD-CODED PART for this notebook: Fixing PARAM  

# NOTE:
# Parameters "SCCP" and "MCCP" until 2017 has been checked and found to be "eksl. LOQ"
# For 2016-2019, see '872_Check_SCCP_MCCP_before2019.Rmd'  
# Example: 98A2 in 2014 (report '98A2 blåskjell ordre 53-14.PDF' in
#   'K:\Prosjekter\Sjøvann\JAMP\2014\analyser\analyserapporter')  
# 

sel <- with(dat_medians, PARAM %in% "SCCP" & MYEAR <= 2014)
dat_medians$PARAM[sel] <- "SCCP eksl. LOQ"

sel <- with(dat_medians, PARAM %in% "MCCP" & MYEAR <= 2014)
dat_medians$PARAM[sel] <- "MCCP eksl. LOQ"
# HARD-CODED PART end


# Select all parameters
dat_medians_sel_1 <- dat_medians %>%
  filter(
    PARAM %in% params,
    TISSUE_NAME %in% tissues) 
message("nrow(dat_medians_sel_1): ", nrow(dat_medians_sel_1))


# HARD-CODED PART for this notebook: "Fixing" Over LOQ for eider duck, all years
sel <- dat_medians_sel_1$LATIN_NAME %in% "Somateria mollissima"
dat_medians_sel_1$Over_LOQ[sel] <- NA    
# HARD-CODED PART end


# HARD-CODED PART for this notebook: Fixing 2018 data

#> 
#> 2018 
#> Already only CCPs
dat_2018_all <- readRDS("../Input_data/01_df_2018_notstandard_2022-11-25_CCP.rds")

# - check units
check <- table(dat_2018_all$UNIT)
if (!identical(names(check), "UG_P_KG"))
  stop("Check units!")

# For adding "incl LOQ" value to tooltip (cod + blue mussel only)
dat_2018_inclLOQ <- dat_2018_all %>%
  filter(NAME %in% c("SCCP inkl. LOQ", "MCCP inkl. LOQ")) %>%
  mutate(NAME = sub("inkl", "eksl", NAME)) %>%   # (for left_join later)
  select(NAME, STATION_CODE, LATIN_NAME, TISSUE_NAME, SAMPLE_NO, VALUE) %>%
  rename(VALUE_incl = VALUE)

# cod + blue mussel data
dat_2018_codmussel <- dat_2018_all %>%
  filter(NAME %in% c("SCCP eksl. LOQ", "MCCP eksl. LOQ")) %>%
  mutate(FLAG1 = ifelse(VALUE == 0, "<", as.character(NA))) %>%
  left_join(dat_2018_inclLOQ, 
            by = c("NAME", "STATION_CODE", "LATIN_NAME", "TISSUE_NAME", "SAMPLE_NO"))

# Check
# dat_2018_codmussel %>%
#   select(STATION_CODE, LATIN_NAME, TISSUE_NAME, SAMPLE_NO, NAME, VALUE, VALUE_incl, FLAG1) %>%
#   View("2018")


#>
#> 2019
#> 
dat_2019_all <- readRDS("../Input_data/01_df_2019_notstandard_2020-08-05.rds") %>%
  filter(NAME %in% c("SCCP eksl. LOQ", "MCCP eksl. LOQ", "SCCP inkl. LOQ", "MCCP inkl. LOQ",
                     "Kortkjedede (SCCP), C10-C13", "Mellomkjedede (MCCP), C14-C17"))

lookup_spec <- dat_2018_all %>%
  distinct(STATION_CODE, LATIN_NAME)
dat_2019_all <- dat_2019_all %>%
  select(-LATIN_NAME) %>%
  left_join(lookup_spec, by = "STATION_CODE")

# - check units
check <- table(dat_2019_all$UNIT)

# if (!identical(names(check), "UG_P_KG"))
#   stop("Check units!")

# hard-code unit after checking  
dat_2019_all$UNIT <- "UG_P_KG"

# Pivot to wide format to get the lacking zeros 
df_SCCP <- dat_2019_all %>%
  filter(grepl("SCCP", NAME)) %>%
  select(STATION_CODE, LATIN_NAME, TISSUE_NAME, SAMPLE_NO, NAME, VALUE) %>%
  pivot_wider(names_from = NAME, values_from = VALUE) %>%
  mutate(
    `SCCP eksl. LOQ` = ifelse(is.na(`SCCP eksl. LOQ`), 0,  `SCCP eksl. LOQ`),
    `SCCP inkl. LOQ` = ifelse(is.na(`SCCP inkl. LOQ`), 0,  `SCCP inkl. LOQ`)
  ) 
df_MCCP <- dat_2019_all %>%
  filter(grepl("MCCP", NAME)) %>%
  select(STATION_CODE, LATIN_NAME, TISSUE_NAME, SAMPLE_NO, NAME, VALUE) %>%
  pivot_wider(names_from = NAME, values_from = VALUE) %>%
  mutate(
    `MCCP eksl. LOQ` = ifelse(is.na(`MCCP eksl. LOQ`), 0,  `MCCP eksl. LOQ`),
    `MCCP inkl. LOQ` = ifelse(is.na(`MCCP inkl. LOQ`), 0,  `MCCP inkl. LOQ`)
  ) 


# VALUE_incl is included for adding "incl LOQ" value to tooltip (cod + blue mussel only)
dat_2019_codmussel <- bind_rows(
  df_SCCP %>% 
    mutate(NAME = "SCCP eksl. LOQ") %>%
    rename(VALUE = `SCCP eksl. LOQ`, VALUE_incl = `SCCP inkl. LOQ`) %>% # View()
    mutate(FLAG1 = ifelse(VALUE == 0, "<", as.character(NA))),
  df_MCCP %>% 
    mutate(NAME = "MCCP eksl. LOQ") %>%
    rename(VALUE = `MCCP eksl. LOQ`, VALUE_incl = `MCCP inkl. LOQ`) %>% # View()
    mutate(FLAG1 = ifelse(VALUE == 0, "<", as.character(NA)))
)

# For manual check
# dat_2019_codmussel %>%
#   select(STATION_CODE, LATIN_NAME, TISSUE_NAME, SAMPLE_NO, NAME, VALUE, VALUE_incl, FLAG1) %>%
#   View("2019")


#>
#> 2020
#> 
dat_2020_all <- readRDS("../Input_data/01_df_2020_notstandard_2022-01-05.rds") %>%
  filter(NAME %in% c("SCCP eksl. LOQ", "MCCP eksl. LOQ", "SCCP inkl. LOQ", "MCCP inkl. LOQ",
                     "Kortkjedede (SCCP), C10-C13", "Mellomkjedede (MCCP), C14-C17"))

# - check units
check <- table(dat_2020_all$UNIT)

# if (!identical(names(check), "UG_P_KG"))
#   stop("Check units!")

# hard-code unit after checking  
dat_2020_all$UNIT <- "UG_P_KG"

# Pivot to wide format to get the lacking zeros 
df_SCCP <- dat_2020_all %>%
  filter(grepl("SCCP", NAME)) %>%
  select(STATION_CODE, LATIN_NAME, TISSUE_NAME, SAMPLE_NO, NAME, VALUE) %>%
  pivot_wider(names_from = NAME, values_from = VALUE) %>%
  mutate(
    `SCCP eksl. LOQ` = ifelse(is.na(`SCCP eksl. LOQ`), 0,  `SCCP eksl. LOQ`),
    `SCCP inkl. LOQ` = ifelse(is.na(`SCCP inkl. LOQ`), 0,  `SCCP inkl. LOQ`)
  ) 
df_MCCP <- dat_2020_all %>%
  filter(grepl("MCCP", NAME)) %>%
  select(STATION_CODE, LATIN_NAME, TISSUE_NAME, SAMPLE_NO, NAME, VALUE) %>%
  pivot_wider(names_from = NAME, values_from = VALUE) %>%
  mutate(
    `MCCP eksl. LOQ` = ifelse(is.na(`MCCP eksl. LOQ`), 0,  `MCCP eksl. LOQ`),
    `MCCP inkl. LOQ` = ifelse(is.na(`MCCP inkl. LOQ`), 0,  `MCCP inkl. LOQ`)
  ) 

# VALUE_incl is included for adding "incl LOQ" value to tooltip (cod + blue mussel only)
dat_2020_codmussel <- bind_rows(
  df_SCCP %>% 
    mutate(NAME = "SCCP eksl. LOQ") %>%
    rename(VALUE = `SCCP eksl. LOQ`, VALUE_incl = `SCCP inkl. LOQ`) %>% # View()
    mutate(FLAG1 = ifelse(VALUE == 0, "<", as.character(NA))),
  df_MCCP %>% 
    mutate(NAME = "MCCP eksl. LOQ") %>%
    rename(VALUE = `MCCP eksl. LOQ`, VALUE_incl = `MCCP inkl. LOQ`) %>% # View()
    mutate(FLAG1 = ifelse(VALUE == 0, "<", as.character(NA)))
)

# For manual check
# dat_2020_codmussel %>%
#   select(STATION_CODE, LATIN_NAME, TISSUE_NAME, SAMPLE_NO, NAME, VALUE, VALUE_incl, FLAG1) %>%
#   View("2020")



#>
#> 2021
#> 
#> This part is different because the data are already fixed

dat_2021_all <- readRDS("../Input_data/01_df_2021_notstandard_2022-09-23.rds") %>%
  filter(NAME %in% c("SCCP eksl. LOQ", "MCCP eksl. LOQ", "SCCP inkl. LOQ", "MCCP inkl. LOQ",
                     "Kortkjedede (SCCP), C10-C13", "Mellomkjedede (MCCP), C14-C17"))

# - check units
check <- table(dat_2021_all$UNIT)
if (!identical(names(check), "NG_P_G"))
  stop("Check units!")

# For adding "incl LOQ" value to tooltip (cod + blue mussel only)
dat_2021_inclLOQ <- dat_2021_all %>%
  filter(NAME %in% c("SCCP inkl. LOQ", "MCCP inkl. LOQ")) %>%
  mutate(NAME = sub("inkl", "eksl", NAME)) %>%   # (for left_join later)
  select(NAME, STATION_CODE, LATIN_NAME, TISSUE_NAME, SAMPLE_NO, VALUE) %>%
  rename(VALUE_incl = VALUE)

# cod + blue mussel data
dat_2021_codmussel <- dat_2021_all %>%
  filter(NAME %in% c("SCCP eksl. LOQ", "MCCP eksl. LOQ")) %>%
  mutate(FLAG1 = as.character(NA)) %>%    # set wrong in script 001 or something...
  left_join(dat_2021_inclLOQ, 
            by = c("NAME", "STATION_CODE", "LATIN_NAME", "TISSUE_NAME", "SAMPLE_NO"))

# Eider duck data
dat_2021_eider_1 <- dat_2021_all %>%
  filter(NAME %in% c("Kortkjedede (SCCP), C10-C13")) %>%
  mutate(NAME = "SCCP eksl. LOQ") 
dat_2021_eider_2 <- dat_2021_all %>%
  filter(NAME %in% c("Mellomkjedede (MCCP), C14-C17")) %>%
  mutate(NAME = "MCCP eksl. LOQ") 

# All data, sample level  
dat_2018_2021 <- bind_rows(
  dat_2018_codmussel %>% mutate(MYEAR = 2018),
  dat_2019_codmussel %>% mutate(MYEAR = 2019),
  dat_2020_codmussel %>% mutate(MYEAR = 2020),
  dat_2021_codmussel %>% mutate(MYEAR = 2021), 
  dat_2021_eider_1 %>% mutate(MYEAR = 2021), 
  dat_2021_eider_2 %>% mutate(MYEAR = 2021))

# For manual check
# dat_2018_2021 %>%
#   select(STATION_CODE, LATIN_NAME, TISSUE_NAME, SAMPLE_NO, NAME, VALUE, VALUE_incl, FLAG1) %>%
#   View("2021")

# Code adapted from script 110, section 3    
dat_2018_2021_med <- dat_2018_2021 %>%
  rename(VALUE_WW = VALUE) %>%        # note: assume w.w.
  group_by(MYEAR, PARAM = NAME, STATION_CODE, LATIN_NAME, TISSUE_NAME) %>%
  summarise(
    N_median = n(), 
    Det_limit = median(VALUE_WW[!is.na(FLAG1)]), 
    Over_LOQ = sum(is.na(FLAG1)),
    Value_min = min(VALUE_WW, na.rm = TRUE),
    Value_p25 = quantile(VALUE_WW, probs = 0.25, na.rm = TRUE),
    Value_p75 = quantile(VALUE_WW, probs = 0.75, na.rm = TRUE),
    Value_max = max(VALUE_WW, na.rm = TRUE),
    Value = median(VALUE_WW, na.rm = TRUE),
    Value_incl = median(VALUE_incl, na.rm = TRUE),
    .groups = "drop") %>%
  mutate(
    UNIT = "UG_P_KG",
    Basis = "WW")


# NOTE:
sel <- dat_2018_2021_med$STATION_CODE %in% "36A1"; sum(sel)
dat_2018_2021_med$STATION_CODE[sel] <- "36A"

# Data to replace
sel1 <- with(dat_medians_sel_1, !LATIN_NAME %in% "Somateria mollissima" & MYEAR %in% 2018:2020)
sel2 <- with(dat_medians_sel_1, MYEAR %in% 2021:2022)

message("nrow(dat_medians_sel_1): ", nrow(dat_medians_sel_1))
dat_medians_sel_1 <- dat_medians_sel_1[!sel1 & !sel2,] %>%
  bind_rows(dat_2018_2021_med)
message("nrow(dat_medians_sel_1): ", nrow(dat_medians_sel_1))

# HARD-CODED PART end


#
# Get stations used in 2021  
#

tab_stations <- dat_medians_sel_1 %>%
  filter(MYEAR == 2021) %>%
  xtabs(~STATION_CODE + PARAM, .)
tab_stations

stations <- row.names(tab_stations)

# Select data for those stations
dat_medians_sel <- dat_medians_sel_1 %>%
  filter(
    STATION_CODE %in% stations,
    Basis == "WW",
    !is.na(Value)
    ) %>%
  left_join(lookup_stations %>% select(STATION_CODE, Station_name, Order),
            by = "STATION_CODE") %>%
  mutate(
    Station = case_when(
      !LATIN_NAME %in% "Somateria mollissima" ~ 
        paste(STATION_CODE, Station_name),
      LATIN_NAME %in% "Somateria mollissima" & TISSUE_NAME == "Blod" ~ 
        paste(STATION_CODE, Station_name, "eider duck blood"),
      LATIN_NAME %in% "Somateria mollissima"  & TISSUE_NAME == "Egg"~ 
        paste(STATION_CODE, Station_name, "eider duck egg")),
    FLAG1 = ifelse(Over_LOQ < 0.5*N_median, "<", as.character(NA))
)

if (FALSE){
  
  xtabs(~MYEAR + STATION_CODE, dat_medians_sel)
  xtabs(~Station, dat_medians_sel)
  
  # years
  dat_medians %>%
    filter(grepl("SCCP", PARAM)) %>%
    filter(MYEAR >= 2000) %>%
    xtabs(~MYEAR + PARAM , .)

}

```


## SCCP (short-chained chlorinated paraffins)   

```{r, include=FALSE}

# pick-data-parameter

# Change 1) heading above, 2) param + plot_title below, 3) lookup_ref_value, 4) caption_text1 and 2

param <- "SCCP eksl. LOQ"
plot_title <- "SCCP excl. LOQ"  

# Add Ref_value 

# HARD-CODED reference values
# check <- read.csv("../Input_data/Lookup_tables/Lookup_EQS_limits.csv")
# check <- read.csv("../Input_data/Lookup_tables/Lookup_proref.csv")
# Ref. species-specific dry weight: https://dome.ices.dk/ohat/trDocuments/2021/help_ac_basis_conversion.html
lookup_ref_value <- tribble(
  ~LATIN_NAME,          ~Ref_value1, ~Basis1, ~Ref_value2, ~Basis2,   ~Perc_dry_weight,   
  "Gadus morhua",           154,        "ww",     6000,        "ww",                NA,
  "Somateria mollissima",   154,        "ww",     6000,        "ww",                NA,
  "Mytilus edulis",       20.26,        "ww",     6000,        "ww",                NA
)

ref_type1 <- "PROREF"
ref_type2 <- "EQS"
ref_basis1 <- "ww"
ref_basis2 <- "ww"

# Used in add_tooltip_text_tiles()
unit <- "µg/kg"

caption_text1 <- paste0(
  "All data are given in µg/kg w.w. <br>", 
  "Measurements for cod are exclusive LOQ (incl. LOQ given in tooltip for 2021) <br>", 
  "Colours show concentration relative to PROREF (154 µg/kg ww for cod). EQS: 6000 µg/kg ww.  <br>", 
  "Note: For <i>Somateria mollissima</i> (eider duck), no PROREF has been developed, but PROREF for cod is used in this figure for illustrative purposes.")

caption_text2 <- paste0(
  "All data are given in µg/kg w.w. <br>", 
  "Measurements are exclusive LOQ (incl. LOQ given in tooltip for 2021) <br>", 
  "Colours show concentration relative to PROREF (20.26 µg/kg ww for blue mussel). EQS: 6000 µg/kg ww.  <br>")

#
# Set reference values
#

# Select data for those stations
# ...and add reference values ans calculate ratios concentration/reference       
dat_medians_param <- dat_medians_sel %>%
  filter(PARAM %in% param) %>%
  left_join(lookup_ref_value, by = "LATIN_NAME") %>%
  mutate(
    Value_dw = Value*Perc_dry_weight/100,
    Refratio1 = case_when(
      Basis1 %in% "ww" ~ Value/Ref_value1,
      Basis1 %in% "dw" ~ Value_dw/Ref_value1),
    Refratio2 = case_when(
      Basis2 %in% "ww" ~ Value/Ref_value2,
      Basis2 %in% "dw" ~ Value_dw/Ref_value2)
    )

# Set Refratio and add tooltips  

if (FALSE){
  # Check plot
  gg <- dat_medians_param %>%
    mutate(Station = fct_rev(Station)) %>%
    ggplot(aes(MYEAR, Station))
  gg + geom_tile(aes(fill = Value))
  gg + geom_tile(aes(fill = Refratio1))
}

```


```{r}

# create-tile-data1

startyr <- 2012
current_year <- 2021

data_tiles <- list()

data_tiles[[1]] <- dat_medians_param %>%
  filter(LATIN_NAME %in% c("Gadus morhua", "Somateria mollissima")) %>%
  filter(MYEAR >= startyr) %>%
  arrange(Order) %>%
  mutate(
    Station = fct_inorder(Station)
  )

data_tiles[[2]] <- dat_medians_param %>%
  filter(LATIN_NAME %in% c("Mytilus edulis")) %>%
  filter(MYEAR >= startyr) %>%
  arrange(Order) %>%
  mutate(
    Station = fct_inorder(Station)
  )

# Check stations:  
# paste(levels(data_tiles[[1]]$Station), collapse = ", ")
# paste(levels(data_tiles[[2]]$Station), collapse = ", ")

```

```{r}

# create-tile-data2

# debugonce(add_tooltip_text_tiles)
for (i in seq_along(data_tiles)){
  data_tiles[[i]] <- data_tiles[[i]] %>% 
    check_unit() %>%     # Checks that the data has only a single unit  
    mutate(Refratio_cut = cut(Refratio1, breaks = c(0,0.5,0.75,0.9,1,2,5,10,20,100))) %>%
    add_tooltip_text_tiles(ref_type1 = "PROREF", ref_type2 = "EQS", unit = "µg/kg")
}


# HARD-CODED for SCCP/MCCP 
for (i in seq_along(data_tiles)){
  data_tiles[[i]] <- data_tiles[[i]] %>%
    mutate(
      Tooltip_txt = case_when(
        MYEAR >= 2018 & !LATIN_NAME %in% "Somateria mollissima" ~ paste0(Tooltip_txt, "<br>Incl. LOQ: ", Value_incl, " ", unit),
        TRUE ~ Tooltip_txt
      )
    )
}
# HARD-CODED end

if (FALSE){

  # Check plot
  gg <- data_tiles[[i]] %>%
    mutate(Station = fct_rev(Station)) %>%
    ggplot(aes(MYEAR, Station))
  gg + geom_tile(aes(fill = Value))
  gg + geom_tile(aes(fill = Refratio1))
  
}

```


```{r, warning=FALSE}

# create-tile-plots

plot_tiles <- list()

for (i in seq_along(data_tiles)){
  tile_colours <- get_tile_colours(data_tiles[[i]])
  plot_tiles[[i]] <- get_tile_plot(data_tiles[[i]], tile_colours)
}

```

```{r, include=FALSE}

# create-trend-data

shape_order <- c("Increasing", "Decreasing", "No change")
colour_order <- shape_order
  
trend_shapes <- c(24, 25, 21) %>% setNames(shape_order)
trend_colours <- c("red3", "green4", "grey20") %>% setNames(colour_order)
trend_fill <- c("red2", "green2", "grey20") %>% setNames(colour_order)

# Data for trend plot
data_trends <- list()

# y range for putting text in the right place in plot data
y_ran <- list()

for (i in seq_along(data_tiles)){
  
  data_trends[[i]] <- get_data_trends(
    data_tiles[[i]], basis = "WW", include_year = 2021, 
    filename_trends = "../Data/125_results_2021_07_output/126_df_trend_2021.rds") %>%
    add_tooltip_text_trends() %>%
    mutate(label_coor = NA)
  
  y_ran[[i]] <- list()
  
  for (type in c("long", "short")){
    
    # y range equals the point estimates 
    y_ran[[i]][[type]] <- data_trends[[i]] %>% 
      filter(Trend_type %in% type) %>% 
      pull(Perc_annual) %>%
      range(na.rm = TRUE)
    y_ran[[i]][[type]] <- range(y_ran[[i]][[type]], 0)
    
    # y_ran is used to set variable 'label_coor', but is also used to set the range in ggplot later
    sel <- data_trends[[i]]$Trend_type %in% type
    data_trends[[i]]$label_coor[sel] <- mean(y_ran[[i]][[type]])
    
  }

  
}

```

```{r, include=FALSE}

# create-trend-plots

plot_trends <- list()

for (i in seq_along(data_tiles)){
  
  plot_trends[[i]] <- list()
  
  for (type in c("long", "short")){
    
    station_levels <- rev(get_station_levels(data_tiles[[i]]))
    data_for_plot <- data_trends[[i]] %>% 
      filter(Trend_type %in% type) %>%
      mutate(Station = factor(Station, levels = station_levels))
    
    plot_trends[[i]][[type]] <- get_trend_plot(data_for_plot, y_ran[[i]][[type]]) 
    
    if (trends_add_station){
      # For testing only (to check that trends are in correct order)
      plot_trends[[i]][[type]] <- plot_trends[[i]][[type]] +
        geom_label(aes(y = label_coor, label = Station))
    }
  
  }

}


```


```{r}

# combine-plots

plot_combo <- list()
for (i in seq_along(data_tiles)){
  plot_combo[[i]] <- get_combo_plot(plot_tiles[[i]], plot_trends[[i]])
}

```
### Cod and eider duck  

```{r}

girafe( ggobj = plot_combo[[1]], width_svg = width_svg, height_svg = height_svg)

```
`r caption_text1`


### Blue mussel  

```{r}

girafe( ggobj = plot_combo[[2]], width_svg = width_svg, height_svg = height_svg)

```

`r caption_text2`




## MCCP (medium-chained chlorinated paraffins)   

```{r, include=FALSE}

# pick-data-parameter

# Change 1) heading above, 2) param + plot_title below, 3) lookup_ref_value, 4) caption_text1 and 2

param <- "MCCP eksl. LOQ"
plot_title <- "MCCP excl. LOQ"  

# Add Ref_value 

# HARD-CODED reference values - hard-coded
# check <- read.csv("../Input_data/Lookup_tables/Lookup_EQS_limits.csv")
# check <- read.csv("../Input_data/Lookup_tables/Lookup_proref.csv")
# Ref. species-specific dry weight: https://dome.ices.dk/ohat/trDocuments/2021/help_ac_basis_conversion.html

lookup_ref_value <- tribble(
  ~LATIN_NAME,          ~Ref_value1, ~Basis1, ~Ref_value2, ~Basis2,   ~Perc_dry_weight,   
  "Gadus morhua",           392.8,        "ww",     170,        "ww",                NA,
  "Somateria mollissima",   392.8,        "ww",     170,        "ww",                NA,
  "Mytilus edulis",          87.6,        "ww",     170,        "ww",                NA
)


ref_type1 <- "PROREF"
ref_type2 <- "EQS"
ref_basis1 <- "ww"
ref_basis2 <- "ww"

# Used in add_tooltip_text_tiles()
unit <- "µg/kg"

caption_text1 <- paste0(
  "All data are given in µg/kg w.w. <br>", 
  "Measurements for cod are exclusive LOQ (incl. LOQ given in tooltip for 2021) <br>", 
  "Colours show concentration relative to PROREF (392.8 µg/kg ww for cod). Red frame = EQS (170 µg/kg w.w.) exceeded.  <br>", 
  "Note: For <i>Somateria mollissima</i> (eider duck), no PROREF has been developed, but PROREF for cod is used in this figure for illustrative purposes.")

caption_text2 <- paste0(
  "All data are given in µg/kg w.w. <br>", 
  "Measurements are exclusive LOQ (incl. LOQ given in tooltip for 2021) <br>", 
  "Colours show concentration relative to PROREF (87.6 µg/kg ww for blue mussel). EQS: 170 µg/kg ww.  <br>")

#
# Set reference values
#

# Select data for those stations
# ...and add reference values ans calculate ratios concentration/reference       
dat_medians_param <- dat_medians_sel %>%
  filter(PARAM %in% param) %>%
  left_join(lookup_ref_value, by = "LATIN_NAME") %>%
  mutate(
    Value_dw = Value*Perc_dry_weight/100,
    Refratio1 = case_when(
      Basis1 %in% "ww" ~ Value/Ref_value1,
      Basis1 %in% "dw" ~ Value_dw/Ref_value1),
    Refratio2 = case_when(
      Basis2 %in% "ww" ~ Value/Ref_value2,
      Basis2 %in% "dw" ~ Value_dw/Ref_value2)
    )

# Set Refratio and add tooltips  

```




```{r}

# create-tile-data1

startyr <- 2012
current_year <- 2021

data_tiles <- list()

data_tiles[[1]] <- dat_medians_param %>%
  filter(LATIN_NAME %in% c("Gadus morhua", "Somateria mollissima")) %>%
  filter(MYEAR >= startyr) %>%
  arrange(Order) %>%
  mutate(
    Station = fct_inorder(Station)
  )

data_tiles[[2]] <- dat_medians_param %>%
  filter(LATIN_NAME %in% c("Mytilus edulis")) %>%
  filter(MYEAR >= startyr) %>%
  arrange(Order) %>%
  mutate(
    Station = fct_inorder(Station)
  )

# Check stations:  
# paste(levels(data_tiles[[1]]$Station), collapse = ", ")
# paste(levels(data_tiles[[2]]$Station), collapse = ", ")

```

```{r}

# create-tile-data2

for (i in seq_along(data_tiles)){
  data_tiles[[i]] <- data_tiles[[i]] %>% 
    check_unit() %>%     # Checks that the data has only a single unit  
    mutate(Refratio_cut = cut(Refratio1, breaks = c(0,0.5,0.75,0.9,1,2,5,10,20,100))) %>%
    add_tooltip_text_tiles(ref_type1 = "PROREF", ref_type2 = "EQS", unit = "µg/kg")
}


# HARD-CODED for SCCP/MCCP 
for (i in seq_along(data_tiles)){
  data_tiles[[i]] <- data_tiles[[i]] %>%
    mutate(
      Tooltip_txt = case_when(
        MYEAR >= 2018 & !LATIN_NAME %in% "Somateria mollissima" ~ paste0(Tooltip_txt, "<br>Incl. LOQ: ", Value_incl, " ", unit),
        TRUE ~ Tooltip_txt
      )
    )
}
# HARD-CODED end

if (FALSE){

  # Check plot
  i <- 1
  gg <- data_tiles[[i]] %>%
    mutate(Station = fct_rev(Station)) %>%
    ggplot(aes(MYEAR, Station))
  gg + geom_tile(aes(fill = Value))
  gg + geom_tile(aes(fill = Refratio1))
  gg + geom_tile(aes(fill = Refratio2))
  
}

```


```{r, warning=FALSE}

# create-tile-plots

plot_tiles <- list()

for (i in seq_along(data_tiles)){
  tile_colours <- get_tile_colours(data_tiles[[i]])
  plot_tiles[[i]] <- get_tile_plot(data_tiles[[i]], tile_colours)
}

```

```{r, include=FALSE}

# create-trend-data

shape_order <- c("Increasing", "Decreasing", "No change")
colour_order <- shape_order
  
trend_shapes <- c(24, 25, 21) %>% setNames(shape_order)
trend_colours <- c("red3", "green4", "grey20") %>% setNames(colour_order)
trend_fill <- c("red2", "green2", "grey20") %>% setNames(colour_order)

# Data for trend plot
data_trends <- list()

# y range for putting text in the right place in plot data
y_ran <- list()

for (i in seq_along(data_tiles)){
  
  data_trends[[i]] <- get_data_trends(
    data_tiles[[i]], basis = "WW", include_year = 2021, 
    filename_trends = "../Data/125_results_2021_07_output/126_df_trend_2021.rds") %>%
    add_tooltip_text_trends() %>%
    mutate(label_coor = NA)
  
  y_ran[[i]] <- list()
  
  for (type in c("long", "short")){
    
    # y range equals the point estimates 
    y_ran[[i]][[type]] <- data_trends[[i]] %>% 
      filter(Trend_type %in% type) %>% 
      pull(Perc_annual) %>%
      range(na.rm = TRUE)
    y_ran[[i]][[type]] <- range(y_ran[[i]][[type]], 0)
    
    # y_ran is used to set variable 'label_coor', but is also used to set the range in ggplot later
    sel <- data_trends[[i]]$Trend_type %in% type
    data_trends[[i]]$label_coor[sel] <- mean(y_ran[[i]][[type]])
    
  }

  
}

```

```{r, include=FALSE}

# create-trend-plots

plot_trends <- list()

for (i in seq_along(data_tiles)){
  
  plot_trends[[i]] <- list()
  
  for (type in c("long", "short")){
    
    station_levels <- rev(get_station_levels(data_tiles[[i]]))
    data_for_plot <- data_trends[[i]] %>% 
      filter(Trend_type %in% type) %>%
      mutate(Station = factor(Station, levels = station_levels))
    
    plot_trends[[i]][[type]] <- get_trend_plot(data_for_plot, y_ran[[i]][[type]]) 
    
    if (trends_add_station){
      # For testing only (to check that trends are in correct order)
      plot_trends[[i]][[type]] <- plot_trends[[i]][[type]] +
        geom_label(aes(y = label_coor, label = Station))
    }
  
  }

}


```


```{r}

# combine-plots

plot_combo <- list()
for (i in seq_along(data_tiles)){
  plot_combo[[i]] <- get_combo_plot(plot_tiles[[i]], plot_trends[[i]])
}

```


### Cod and eider duck  

```{r}

girafe( ggobj = plot_combo[[1]], width_svg = width_svg, height_svg = height_svg)

```
`r caption_text1`


### Blue mussel  

```{r}

girafe( ggobj = plot_combo[[2]], width_svg = width_svg, height_svg = height_svg)

```
`r caption_text2`




