---
title: "Fact sheet - PAH"
author: "DHJ"
date: "2022-11-01"
output: 
  html_document:
    toc: true
    toc_float: true

---


```{r, include=FALSE}
#
# NOTE: MORE 'params' SETTINGS HAVE BEEN ADDED TO SCRIPT 434 (CALLED BELOW)
# SINCE THIS SCRIPT WAS RUN. THIS SCRIPT PROBABLY NEEDS TO BE UPDATED TO 
# TAKE THAT INTO ACCOUNT, IF YOU WANT TO RERERUN IT. SEE 'METALS' Rmd FOR EXAMPLE.
#

lookup_eqs <- subset(
  read.csv("../Input_data/Lookup_tables/Lookup_EQS_limits.csv"),
  Basis == "WW")

if (FALSE){
  # Code for getting parameters for 'param_values' below 
  library(dplyr)
  # dat_raw <- readRDS("../Data/109_adjusted_data_2022-09-23.rds")  
  dat_med <- readRDS("../Data/110_mediandata_updated_2022-09-23.rds")  
  dat_groups <- read.csv("../Input_data/Lookup_tables/Lookup table - substance groups.csv")
  dat_med2 <- dplyr::left_join(dat_med, subset(dat_groups, select = c(PARAM, MGR.Group)))
  xtabs(~MGR.Group, dat_med2 %>% filter(MYEAR == 2021) %>% distinct(MGR.Group, PARAM))
  
  # Choose group(s)
  group <- "PAH"
  tab <- xtabs(~PARAM, dat_med2 %>% filter(MYEAR == 2021 & MGR.Group %in% group))
  tab
  param_values <- names(tab[tab > 100])
  param_values <- names(tab)
  # For copy-paste to code below:
  dat_groups %>% 
    filter(PARAM %in% param_values) %>% # View()
    arrange(Parameter.Name) %>%            # order alphabetically by Parameter.Name, not PARAM
    pull(PARAM) %>%
    dput()

  # check 'Parameter.Name' - must exist for all
  check <- dat_groups %>% filter(PARAM %in% param_values) %>% pull(Parameter.Name)
  if (sum(is.na(check)) > 0){
    stop("Parameter.Name - must exist for all")
  }
  
  # Also: For each new parameter group, remember to change 1) filename and 2) title
}

```


```{r, echo=FALSE, results='asis', warning=FALSE, message=FALSE}

# both "FALSE" and "TRUE" seems to work for 'called_from_mother' 

params <- list(
  param = "BAA",
  basis_medians = "WW",
  basis_trends = "WW",
  eqsplot = "ordinary",
  prorefplot = "TRUE",
  include_trend = "TRUE",
  serieslastuntil = 2021,
  called_from_mother = "TRUE",
  species3 = "Mytilus edulis"
)


```

<style type="text/css">
div.main-container {
  max-width: 1800px;
  margin-left: auto;
  margin-right: auto;
}
</style>


```{r, echo=FALSE, results='asis', warning=FALSE, message=FALSE}

param_values <- c("ACNE", "ACNLE", "ANT", "BAA", "BAP", "BBJF", "BGHIP", "BKF", 
"CHR", "DBA3A", "FLE", "FLU", "ICDP", "NAP", "PA", "PYR")

# param_values <- c("BAA")

for (param in param_values){
  
  params$param <- param
  
  if (param %in% lookup_eqs$PARAM){
    if (param %in% c("BAA", "ANT")){
      params$eqsplot <- "log"
    } else {
      params$eqsplot <- "ordinary"
    }
  } else {
      params$eqsplot <- "FALSE"
  }
  
  res <- knitr::knit_child('../434_Report_parameter_interactive_nochunklabels.Rmd', quiet = TRUE)
  cat(res, sep = '\n')

}

# Alternative:
# ```{r call_child, child = '434_Report_parameter_interactive.Rmd'}
# ```

```

